services:
  llooma:
    image: ghcr.io/cedhuf/llooma:latest
    restart: unless-stopped
    ports:
      - '${HOST_PORT:-4173}:4173'
    environment:
      - VITE_ALLOWED_HOSTS=${VITE_ALLOWED_HOSTS:-localhost}
