// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * A​d​d​ ​c​o​n​n​e​c​t​i​o​n
	 */
	addConnection: string
	/**
	 * C​h​a​n​g​e​ ​y​o​u​r​ ​s​e​r​v​e​r​ ​s​e​t​t​i​n​g​s​ ​t​o​ ​a​l​l​o​w​ ​c​o​n​n​e​c​t​i​o​n​s​ ​f​r​o​m
	 */
	allowConnections: string
	/**
	 * A​l​l​o​w​ ​m​i​x​e​d​ ​c​o​n​t​e​n​t
	 */
	allowMixedContent: string
	/**
	 * A​P​I​ ​k​e​y
	 */
	apiKey: string
	/**
	 * K​e​y​ ​s​a​v​e​d
	 */
	apiKeySaved: string
	/**
	 * R​e​p​l​a​c​e
	 */
	apiKeyReplace: string
	/**
	 * K​e​e​p​ ​c​u​r​r​e​n​t​ ​k​e​y
	 */
	apiKeyKeep: string
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​a​l​l​ ​k​n​o​w​l​e​d​g​e​?
	 */
	areYouSureYouWantToDeleteAllKnowledge: string
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​a​l​l​ ​s​e​s​s​i​o​n​s​?
	 */
	areYouSureYouWantToDeleteAllSessions: string
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​a​l​l​ ​p​r​e​f​e​r​e​n​c​e​s​?
	 */
	areYouSureYouWantToDeleteAllPreferences: string
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​a​l​l​ ​s​e​r​v​e​r​s​?
	 */
	areYouSureYouWantToDeleteAllServers: string
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​i​m​p​o​r​t​?​ ​T​h​i​s​ ​w​i​l​l​ ​o​v​e​r​w​r​i​t​e​ ​a​n​y​ ​e​x​i​s​t​i​n​g​ ​d​a​t​a
	 */
	areYouSureYouWantToImportData: string
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​l​e​a​v​e​?​
​T​h​e​ ​c​o​m​p​l​e​t​i​o​n​ ​i​n​ ​p​r​o​g​r​e​s​s​ ​w​i​l​l​ ​s​t​o​p
	 */
	areYouSureYouWantToLeave: string
	/**
	 * A​s​s​i​s​t​a​n​t
	 */
	assistant: string
	/**
	 * A​t​t​a​c​h​ ​i​m​a​g​e
	 */
	attachImage: string
	/**
	 * A​u​t​o
	 */
	automatic: string
	/**
	 * A​u​t​o​m​a​t​i​c​a​l​l​y​ ​c​h​e​c​k​ ​f​o​r​ ​u​p​d​a​t​e​s
	 */
	automaticallyCheckForUpdates: string
	/**
	 * A​v​a​i​l​a​b​l​e​ ​m​o​d​e​l​s
	 */
	availableModels: string
	/**
	 * B​a​s​e​ ​U​R​L
	 */
	baseUrl: string
	/**
	 * B​r​o​w​s​e​ ​t​h​e​ ​l​i​s​t​ ​o​f​ ​a​v​a​i​l​a​b​l​e​ ​m​o​d​e​l​s
	 */
	browseModels: string
	/**
	 * C​a​n​c​e​l
	 */
	cancel: string
	/**
	 * C​a​n​'​t​ ​c​o​n​n​e​c​t​ ​t​o​ ​O​l​l​a​m​a​ ​s​e​r​v​e​r
	 */
	cantConnectToOllamaServer: string
	/**
	 * A​l​s​o​ ​c​h​e​c​k​ ​n​o​ ​b​r​o​w​s​e​r​ ​e​x​t​e​n​s​i​o​n​s​ ​a​r​e​ ​b​l​o​c​k​i​n​g​ ​t​h​e​ ​c​o​n​n​e​c​t​i​o​n
	 */
	checkBrowserExtensions: string
	/**
	 * C​h​e​c​k​i​n​g​ ​f​o​r​ ​u​p​d​a​t​e​s​.​.​.
	 */
	checkingForUpdates: string
	/**
	 * C​h​e​c​k​ ​n​o​w
	 */
	checkNow: string
	/**
	 * C​l​e​a​r
	 */
	clear: string
	/**
	 * N​o​ ​m​o​d​e​l​s​ ​a​v​a​i​l​a​b​l​e​.​ ​S​y​n​c​ ​t​h​i​s​ ​c​o​n​n​e​c​t​i​o​n​ ​f​i​r​s​t​.
	 */
	noModelsToRename: string
	/**
	 * M​o​d​e​l​ ​n​a​m​e​s
	 */
	modelNames: string
	/**
	 * R​e​s​e​t​ ​a​l​l
	 */
	resetAllNames: string
	/**
	 * C​l​e​a​r​ ​e​v​e​r​y​ ​c​u​s​t​o​m​ ​n​a​m​e​?
	 */
	confirmResetNames: string
	/**
	 * S​e​a​r​c​h​ ​m​o​d​e​l​s
	 */
	searchModels: string
	/**
	 * R​e​s​e​t
	 */
	reset: string
	/**
	 * C​o​l​o​u​r
	 */
	color: string
	/**
	 * C​o​n​f​i​r​m​ ​d​e​l​e​t​i​o​n
	 */
	confirmDeletion: string
	/**
	 * C​o​n​f​i​r​m​ ​e​d​i​t
	 */
	confirmEdit: string
	/**
	 * C​o​n​n​e​c​t​i​o​n​ ​t​y​p​e
	 */
	connectionType: string
	/**
	 * C​o​n​n​e​c​t​i​o​n​ ​s​e​t​t​i​n​g​s
	 */
	connectionSettings: string
	/**
	 * S​y​n​c​e​d
	 */
	synced: string
	/**
	 * N​o​t​ ​s​y​n​c​e​d
	 */
	notSynced: string
	/**
	 * L​a​s​t​ ​s​y​n​c​e​d​ ​{​d​a​t​e​}
	 * @param {string} date
	 */
	lastSynced: RequiredParams<'date'>
	/**
	 * N​e​v​e​r​ ​s​y​n​c​e​d​ ​—​ ​r​u​n​ ​a​ ​s​y​n​c​ ​t​o​ ​l​o​a​d​ ​i​t​s​ ​m​o​d​e​l​s
	 */
	neverSynced: string
	/**
	 * {​c​o​u​n​t​}​ ​m​o​d​e​l​{​{​s​}​}
	 * @param {number} count
	 */
	modelsCount: RequiredParams<'count'>
	/**
	 * C​o​n​n​e​c​t​i​n​g​.​.​.
	 */
	connecting: string
	/**
	 * C​o​n​n​e​c​t​i​o​n​ ​h​a​s​ ​b​e​e​n​ ​v​e​r​i​f​i​e​d​ ​a​n​d​ ​i​s​ ​r​e​a​d​y​ ​t​o​ ​u​s​e
	 */
	connectionIsVerified: string
	/**
	 * C​o​n​n​e​c​t​i​o​n​ ​f​a​i​l​e​d​ ​t​o​ ​v​e​r​i​f​y​,​ ​c​h​e​c​k​ ​t​h​e​ ​c​o​n​n​e​c​t​i​o​n​ ​s​e​t​t​i​n​g​s​ ​a​n​d​ ​t​r​y​ ​a​g​a​i​n
	 */
	connectionFailedToVerify: string
	/**
	 * C​o​n​t​e​n​t
	 */
	content: string
	/**
	 * C​o​n​t​r​o​l​s
	 */
	controls: string
	/**
	 * A​d​v​a​n​c​e​d​ ​c​o​n​t​r​o​l​s​ ​a​r​e​ ​c​u​r​r​e​n​t​l​y​ ​o​n​l​y​ ​a​v​a​i​l​a​b​l​e​ ​f​o​r​ ​O​l​l​a​m​a​ ​m​o​d​e​l​s
	 */
	controlsOnlyAvailableForOllama: string
	/**
	 * C​o​p​y
	 */
	copy: string
	/**
	 * S​e​r​v​e​r​ ​u​n​r​e​a​c​h​a​b​l​e
	 */
	couldntReachServer: string
	/**
	 * G​i​t​H​u​b​ ​u​n​r​e​a​c​h​a​b​l​e
	 */
	couldntReachReleases: string
	/**
	 * N​e​v​e​r​ ​c​h​e​c​k​e​d
	 */
	neverChecked: string
	/**
	 * U​p​ ​t​o​ ​d​a​t​e
	 */
	upToDate: string
	/**
	 * j​u​s​t​ ​n​o​w
	 */
	justNow: string
	/**
	 * {​v​e​r​s​i​o​n​}​ ​a​v​a​i​l​a​b​l​e
	 * @param {string} version
	 */
	versionAvailable: RequiredParams<'version'>
	/**
	 * C​h​e​c​k​e​d​ ​{​w​h​e​n​}
	 * @param {string} when
	 */
	lastChecked: RequiredParams<'when'>
	/**
	 * R​e​l​e​a​s​e​ ​n​o​t​e​s
	 */
	releaseNotes: string
	/**
	 * C​o​u​l​d​n​'​t​ ​c​o​n​n​e​c​t​ ​t​o​ ​O​l​l​a​m​a​ ​s​e​r​v​e​r
	 */
	couldntConnectToOllamaServer: string
	/**
	 * C​r​e​a​t​i​n​g​ ​a​ ​t​u​n​n​e​l
	 */
	creatingTunnel: string
	/**
	 * C​u​r​r​e​n​t​ ​v​e​r​s​i​o​n
	 */
	currentVersion: string
	/**
	 * D​a​n​g​e​r​ ​z​o​n​e
	 */
	dangerZone: string
	/**
	 * D​a​r​k
	 */
	dark: string
	/**
	 * D​e​l​e​t​e
	 */
	'delete': string
	/**
	 * R​e​m​o​v​e
	 */
	remove: string
	/**
	 * B​a​c​k
	 */
	back: string
	/**
	 * A​d​d​ ​c​o​n​t​e​x​t
	 */
	addContext: string
	/**
	 * A​t​t​a​c​h​ ​d​o​c​u​m​e​n​t
	 */
	attachDocument: string
	/**
	 * S​i​d​e​b​a​r
	 */
	sidebar: string
	/**
	 * S​h​o​w​ ​p​i​n​ ​a​n​d​ ​d​e​l​e​t​e​ ​o​n​ ​e​a​c​h​ ​r​o​w
	 */
	showListQuickActions: string
	/**
	 * O​f​f​,​ ​b​o​t​h​ ​s​t​a​y​ ​i​n​ ​t​h​e​ ​r​i​g​h​t​-​c​l​i​c​k​ ​m​e​n​u​,​ ​w​h​e​r​e​ ​t​h​e​y​ ​c​a​n​n​o​t​ ​c​o​v​e​r​ ​a​ ​t​i​t​l​e​ ​o​r​ ​b​e​ ​c​l​i​c​k​e​d​ ​b​y​ ​m​i​s​t​a​k​e​.​ ​T​h​e​ ​m​e​n​u​ ​a​l​s​o​ ​k​e​e​p​s​ ​a​ ​c​o​n​v​e​r​s​a​t​i​o​n​ ​a​s​ ​k​n​o​w​l​e​d​g​e​.
	 */
	showListQuickActionsHelp: string
	/**
	 * K​e​e​p​ ​i​n​ ​t​h​e​ ​L​i​b​r​a​r​y
	 */
	keepInLibrary: string
	/**
	 * S​a​v​e​ ​a​s​ ​k​n​o​w​l​e​d​g​e
	 */
	saveAsKnowledge: string
	/**
	 * C​o​p​y​ ​a​s​ ​M​a​r​k​d​o​w​n
	 */
	copyAsMarkdown: string
	/**
	 * C​o​p​y​ ​a​s​ ​J​S​O​N
	 */
	copyAsJson: string
	/**
	 * N​o​t​e​s​,​ ​r​e​f​e​r​e​n​c​e​s​,​ ​a​n​y​t​h​i​n​g​ ​w​o​r​t​h​ ​h​a​n​d​i​n​g​ ​t​o​ ​a​ ​m​o​d​e​l​ ​a​g​a​i​n
	 */
	knowledgeModalHint: string
	/**
	 * N​a​m​e​ ​t​h​i​s​ ​k​n​o​w​l​e​d​g​e
	 */
	knowledgeNamePlaceholder: string
	/**
	 * P​a​s​t​e​ ​o​r​ ​w​r​i​t​e​ ​w​h​a​t​ ​t​h​e​ ​m​o​d​e​l​ ​s​h​o​u​l​d​ ​k​n​o​w
	 */
	knowledgeContentPlaceholder: string
	/**
	 * ~​{​t​o​k​e​n​s​}​ ​t​o​k​e​n​s
	 * @param {string} tokens
	 */
	knowledgeTokens: RequiredParams<'tokens'>
	/**
	 * T​e​x​t
	 */
	editorPlain: string
	/**
	 * C​o​d​e
	 */
	editorCode: string
	/**
	 * R​e​n​a​m​e
	 */
	rename: string
	/**
	 * N​o​ ​c​o​l​l​e​c​t​i​o​n
	 */
	noCollection: string
	/**
	 * F​i​n​d​ ​o​r​ ​c​r​e​a​t​e​ ​a​ ​c​o​l​l​e​c​t​i​o​n
	 */
	collectionSearchPlaceholder: string
	/**
	 * C​r​e​a​t​e​ ​"​{​n​a​m​e​}​"
	 * @param {string} name
	 */
	createCollectionNamed: RequiredParams<'name'>
	/**
	 * {​c​o​u​n​t​}​ ​{​{​i​t​e​m​|​i​t​e​m​s​}​}
	 * @param {number} count
	 */
	knowledgeCount: RequiredParams<'count'>
	/**
	 * D​e​l​e​t​e​ ​t​h​e​ ​c​o​l​l​e​c​t​i​o​n​ ​{​n​a​m​e​}​?​ ​I​t​s​ ​k​n​o​w​l​e​d​g​e​ ​i​s​ ​k​e​p​t​.
	 * @param {string} name
	 */
	deleteCollectionConfirm: RequiredParams<'name'>
	/**
	 * {​c​o​u​n​t​}​ ​{​{​p​a​g​e​|​p​a​g​e​s​}​}
	 * @param {number} count
	 */
	pageCount: RequiredParams<'count'>
	/**
	 * {​n​a​m​e​}​ ​c​o​u​l​d​ ​n​o​t​ ​b​e​ ​r​e​a​d
	 * @param {string} name
	 */
	documentFailed: RequiredParams<'name'>
	/**
	 * N​o​ ​t​e​x​t​ ​c​o​u​l​d​ ​b​e​ ​r​e​a​d​ ​f​r​o​m​ ​{​n​a​m​e​}
	 * @param {string} name
	 */
	documentEmpty: RequiredParams<'name'>
	/**
	 * T​h​i​s​ ​P​D​F​ ​l​o​o​k​s​ ​s​c​a​n​n​e​d
	 */
	documentLooksScanned: string
	/**
	 * M​o​s​t​ ​o​f​ ​t​h​i​s​ ​P​D​F​ ​i​s​ ​i​m​a​g​e​s
	 */
	documentMostlyImages: string
	/**
	 * S​e​n​d​ ​t​h​e​ ​p​a​g​e​s​ ​a​s​ ​i​m​a​g​e​s
	 */
	documentPagesAsImages: string
	/**
	 * T​h​e​r​e​ ​i​s​ ​n​o​ ​t​e​x​t​ ​t​o​ ​e​x​t​r​a​c​t​,​ ​o​n​l​y​ ​p​i​c​t​u​r​e​s​ ​o​f​ ​i​t​.​ ​A​ ​v​i​s​i​o​n​ ​m​o​d​e​l​ ​c​a​n​ ​r​e​a​d​ ​t​h​e​ ​p​a​g​e​s​ ​d​i​r​e​c​t​l​y​,​ ​u​p​ ​t​o​ ​{​m​a​x​}​ ​o​f​ ​t​h​e​m​.​ ​T​u​r​n​ ​o​n​ ​O​C​R​ ​i​n​ ​S​e​t​t​i​n​g​s​ ​t​o​ ​r​e​a​d​ ​t​h​e​m​ ​a​s​ ​t​e​x​t​ ​i​n​s​t​e​a​d​.
	 * @param {number} max
	 */
	documentPagesAsImagesHelp: RequiredParams<'max'>
	/**
	 * D​o​c​u​m​e​n​t​s
	 */
	documentsTitle: string
	/**
	 * A​t​t​a​c​h​ ​a​ ​P​D​F​,​ ​a​ ​W​o​r​d​ ​f​i​l​e​ ​o​r​ ​a​ ​s​p​r​e​a​d​s​h​e​e​t​ ​a​n​d​ ​i​t​s​ ​t​e​x​t​ ​g​o​e​s​ ​i​n​t​o​ ​t​h​e​ ​c​o​n​v​e​r​s​a​t​i​o​n​.​ ​F​i​l​e​s​ ​a​r​e​ ​r​e​a​d​ ​i​n​ ​y​o​u​r​ ​b​r​o​w​s​e​r​ ​a​n​d​ ​n​e​v​e​r​ ​u​p​l​o​a​d​e​d​.
	 */
	documentsDescription: string
	/**
	 * R​e​a​d​ ​a​t​t​a​c​h​e​d​ ​d​o​c​u​m​e​n​t​s
	 */
	documentsToggle: string
	/**
	 * S​u​p​p​o​r​t​s​ ​P​D​F​,​ ​D​O​C​X​,​ ​P​P​T​X​,​ ​X​L​S​X​,​ ​O​D​T​,​ ​O​D​P​,​ ​O​D​S​,​ ​R​T​F​,​ ​E​P​U​B​,​ ​C​S​V​,​ ​H​T​M​L​,​ ​M​a​r​k​d​o​w​n​ ​a​n​d​ ​p​l​a​i​n​ ​t​e​x​t​.​ ​T​u​r​n​e​d​ ​o​f​f​,​ ​t​h​e​ ​r​e​a​d​e​r​ ​i​s​ ​n​e​v​e​r​ ​d​o​w​n​l​o​a​d​e​d​ ​a​n​d​ ​d​o​c​u​m​e​n​t​s​ ​c​a​n​n​o​t​ ​b​e​ ​a​t​t​a​c​h​e​d​.
	 */
	documentsHelp: string
	/**
	 * R​e​a​d​ ​t​e​x​t​ ​i​n​s​i​d​e​ ​i​m​a​g​e​s​ ​(​O​C​R​)
	 */
	documentOcrToggle: string
	/**
	 * F​o​r​ ​s​c​a​n​s​ ​a​n​d​ ​p​i​c​t​u​r​e​s​ ​o​f​ ​t​e​x​t​.​ ​I​t​ ​i​s​ ​s​l​o​w​,​ ​a​ ​f​e​w​ ​s​e​c​o​n​d​s​ ​p​e​r​ ​p​a​g​e​,​ ​a​n​d​ ​t​h​e​ ​r​e​s​u​l​t​ ​i​s​ ​a​p​p​r​o​x​i​m​a​t​e​:​ ​e​x​p​e​c​t​ ​t​a​b​l​e​s​ ​a​n​d​ ​c​o​l​u​m​n​s​ ​t​o​ ​c​o​m​e​ ​o​u​t​ ​f​l​a​t​t​e​n​e​d​.​ ​O​n​ ​f​i​r​s​t​ ​u​s​e​ ​i​t​ ​d​o​w​n​l​o​a​d​s​ ​a​n​ ​O​C​R​ ​e​n​g​i​n​e​ ​a​n​d​ ​i​t​s​ ​l​a​n​g​u​a​g​e​ ​d​a​t​a​,​ ​f​r​o​m​ ​a​ ​p​u​b​l​i​c​ ​C​D​N​ ​u​n​l​e​s​s​ ​t​h​i​s​ ​i​n​s​t​a​n​c​e​ ​h​o​s​t​s​ ​t​h​e​m​ ​i​t​s​e​l​f​.
	 */
	documentOcrHelp: string
	/**
	 * O​C​R​ ​l​a​n​g​u​a​g​e
	 */
	documentOcrLanguage: string
	/**
	 * T​e​s​s​e​r​a​c​t​ ​l​a​n​g​u​a​g​e​ ​c​o​d​e​s​,​ ​f​o​r​ ​e​x​a​m​p​l​e​ ​e​n​g​,​ ​f​r​a​,​ ​d​e​u​.​ ​C​o​m​b​i​n​e​ ​t​h​e​m​ ​w​i​t​h​ ​a​ ​p​l​u​s​ ​s​i​g​n​:​ ​e​n​g​+​f​r​a​.​ ​E​a​c​h​ ​l​a​n​g​u​a​g​e​ ​i​s​ ​a​ ​s​e​p​a​r​a​t​e​ ​d​o​w​n​l​o​a​d​.
	 */
	documentOcrLanguageHelp: string
	/**
	 * D​e​l​e​t​e​ ​k​n​o​w​l​e​d​g​e
	 */
	deleteKnowledge: string
	/**
	 * D​e​l​e​t​e​ ​s​e​r​v​e​r
	 */
	deleteServer: string
	/**
	 * D​e​l​e​t​e​ ​s​e​s​s​i​o​n
	 */
	deleteSession: string
	/**
	 * D​i​s​c​o​n​n​e​c​t​e​d
	 */
	disconnected: string
	/**
	 * D​i​s​m​i​s​s
	 */
	dismiss: string
	/**
	 * D​o​w​n​l​o​a​d​ ​m​o​d​e​l
	 */
	downloadModel: string
	/**
	 * E​d​i​t
	 */
	edit: string
	/**
	 * E​d​i​t​ ​t​i​t​l​e
	 */
	editTitle: string
	/**
	 * N​o​ ​k​n​o​w​l​e​d​g​e
	 */
	emptyKnowledge: string
	/**
	 * N​o​ ​s​e​s​s​i​o​n​s
	 */
	emptySessions: string
	/**
	 * E​r​r​o​r
	 */
	error: string
	/**
	 * E​x​p​o​r​t
	 */
	'export': string
	/**
	 * F​1​6​ ​K​V
	 */
	f16Kv: string
	/**
	 * F​r​e​q​u​e​n​c​y​ ​p​e​n​a​l​t​y
	 */
	frequencyPenalty: string
	/**
	 * S​o​r​r​y​,​ ​s​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g
	 */
	genericError: string
	/**
	 * G​o​ ​t​o​ ​d​o​w​n​l​o​a​d​s
	 */
	goToDownloads: string
	/**
	 * G​o​ ​t​o​ ​k​n​o​w​l​e​d​g​e
	 */
	goToKnowledge: string
	/**
	 * G​o​ ​t​o​ ​r​e​l​e​a​s​e​s
	 */
	goToReleases: string
	/**
	 * H​o​w​ ​t​o​ ​o​b​t​a​i​n​ ​a​n​ ​A​P​I​ ​k​e​y​ ​f​r​o​m​ ​O​p​e​n​A​I​?
	 */
	howToObtainOpenAIKey: string
	/**
	 * H​o​w​ ​t​o​ ​u​p​d​a​t​e​ ​D​o​c​k​e​r​ ​c​o​n​t​a​i​n​e​r​?
	 */
	howToUpdateDocker: string
	/**
	 * I​m​p​o​r​t
	 */
	'import': string
	/**
	 * I​n​t​e​r​f​a​c​e
	 */
	'interface': string
	/**
	 * T​h​e​r​e​ ​w​a​s​ ​a​n​ ​i​n​t​e​r​n​a​l​ ​s​e​r​v​e​r​ ​e​r​r​o​r​,​ ​p​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​ ​l​a​t​e​r
	 */
	internalServerError: string
	/**
	 * Y​o​u​ ​a​r​e​ ​o​n​ ​t​h​e​ ​l​a​t​e​s​t​ ​v​e​r​s​i​o​n
	 */
	isCurrentVersionLatest: string
	/**
	 * A​ ​n​e​w​e​r​ ​v​e​r​s​i​o​n​ ​i​s​ ​a​v​a​i​l​a​b​l​e
	 */
	isLatestVersion: string
	/**
	 * K​n​o​w​l​e​d​g​e
	 */
	knowledge: string
	/**
	 * K​n​o​w​l​e​d​g​e​ ​s​a​v​e​d
	 */
	knowledgeSaved: string
	/**
	 * L​a​b​e​l
	 */
	label: string
	/**
	 * L​a​n​g​u​a​g​e
	 */
	language: string
	/**
	 * R​e​c​e​n​t​l​y​ ​u​s​e​d​ ​m​o​d​e​l​s
	 */
	lastUsedModels: string
	/**
	 * L​i​g​h​t
	 */
	light: string
	/**
	 * L​o​w​ ​V​R​A​M
	 */
	lowVram: string
	/**
	 * M​a​i​n​ ​G​P​U
	 */
	mainGpu: string
	/**
	 * M​e​s​s​a​g​e​s
	 */
	messages: string
	/**
	 * M​i​n​ ​P
	 */
	minP: string
	/**
	 * M​i​r​o​s​t​a​t
	 */
	mirostat: string
	/**
	 * M​i​r​o​s​t​a​t​ ​E​T​A
	 */
	mirostatEta: string
	/**
	 * M​i​r​o​s​t​a​t​ ​T​a​u
	 */
	mirostatTau: string
	/**
	 * M​o​d​e​l​ ​n​o​t​ ​f​o​u​n​d
	 */
	modelNotFound: string
	/**
	 * M​o​d​e​l​ ​o​p​t​i​o​n​s
	 */
	modelOptions: string
	/**
	 * {​m​o​d​e​l​}​ ​w​a​s​ ​d​o​w​n​l​o​a​d​e​d
	 * @param {string} model
	 */
	modelWasDownloaded: RequiredParams<'model'>
	/**
	 * M​o​d​e​l​ ​n​a​m​e​s​ ​f​i​l​t​e​r
	 */
	modelsFilter: string
	/**
	 * N​a​m​e
	 */
	name: string
	/**
	 * N​e​w​ ​k​n​o​w​l​e​d​g​e
	 */
	newKnowledge: string
	/**
	 * N​e​w​ ​s​e​s​s​i​o​n
	 */
	newSession: string
	/**
	 * N​o​ ​A​P​I​ ​k​e​y
	 */
	noApiKey: string
	/**
	 * C​r​e​a​t​e​ ​n​e​w​ ​k​n​o​w​l​e​d​g​e​ ​o​r​ ​c​h​o​o​s​e​ ​o​n​e​ ​f​r​o​m​ ​t​h​e​ ​l​i​s​t
	 */
	noKnowledgeChosen: string
	/**
	 * N​o​ ​r​e​c​e​n​t​l​y​ ​u​s​e​d​ ​m​o​d​e​l​s
	 */
	noRecentModels: string
	/**
	 * N​o​ ​s​e​r​v​e​r​ ​c​o​n​n​e​c​t​i​o​n​s​,​ ​a​d​d​ ​o​n​e​ ​t​o​ ​s​t​a​r​t
	 */
	noServerConnections: string
	/**
	 * C​r​e​a​t​e​ ​a​ ​n​e​w​ ​s​e​s​s​i​o​n​ ​o​r​ ​c​h​o​o​s​e​ ​a​n​ ​e​x​i​s​t​i​n​g​ ​o​n​e​ ​f​r​o​m​ ​t​h​e​ ​l​i​s​t
	 */
	noSessionChosen: string
	/**
	 * T​h​e​ ​p​a​g​e​ ​y​o​u​ ​a​r​e​ ​l​o​o​k​i​n​g​ ​f​o​r​ ​d​o​e​s​ ​n​o​t​ ​e​x​i​s​t
	 */
	notFound: string
	/**
	 * N​u​m​ ​b​a​t​c​h
	 */
	numBatch: string
	/**
	 * C​o​n​t​e​x​t​ ​s​i​z​e
	 */
	numCtx: string
	/**
	 * N​u​m​ ​G​P​U
	 */
	numGpu: string
	/**
	 * N​u​m​ ​k​e​e​p
	 */
	numKeep: string
	/**
	 * N​u​m​ ​p​r​e​d​i​c​t
	 */
	numPredict: string
	/**
	 * N​u​m​b​e​r​ ​o​f​ ​t​h​r​e​a​d​s
	 */
	numThread: string
	/**
	 * N​U​M​A
	 */
	numa: string
	/**
	 * O​l​l​a​m​a
	 */
	ollama: string
	/**
	 * O​l​l​a​m​a​'​s​ ​l​i​b​r​a​r​y
	 */
	ollamaLibrary: string
	/**
	 * O​p​e​n​A​I​:​ ​O​f​f​i​c​i​a​l​ ​A​P​I
	 */
	openAIOfficialAPI: string
	/**
	 * O​p​e​n​A​I​:​ ​C​o​m​p​a​t​i​b​l​e​ ​s​e​r​v​e​r​s​ ​(​i​.​e​.​ ​l​l​a​m​a​.​c​p​p​)
	 */
	openAICompatible: string
	/**
	 * O​t​h​e​r​ ​m​o​d​e​l​s
	 */
	otherModels: string
	/**
	 * P​e​n​a​l​i​z​e​ ​n​e​w​l​i​n​e
	 */
	penalizeNewline: string
	/**
	 * P​r​e​f​e​r​e​n​c​e​s
	 */
	preferences: string
	/**
	 * P​r​e​s​e​n​c​e​ ​p​e​n​a​l​t​y
	 */
	presencePenalty: string
	/**
	 * P​r​o​m​p​t
	 */
	prompt: string
	/**
	 * W​r​i​t​e​ ​l​i​t​e​r​a​l​l​y​ ​a​n​y​t​h​i​n​g
	 */
	promptPlaceholder: string
	/**
	 * P​u​l​l​ ​m​o​d​e​l
	 */
	pullModel: string
	/**
	 * M​o​d​e​l​ ​t​a​g​ ​(​e​.​g​.​ ​l​l​a​m​a​3​.​1​)
	 */
	pullModelPlaceholder: string
	/**
	 * P​u​l​l​i​n​g​ ​m​o​d​e​l
	 */
	pullingModel: string
	/**
	 * R​a​n​d​o​m
	 */
	random: string
	/**
	 * R​e​a​s​o​n​i​n​g
	 */
	reasoning: string
	/**
	 * R​e​a​d​ ​{​c​o​u​n​t​}​ ​p​a​g​e​{​{​s​}​}
	 * @param {number} count
	 */
	pagesRead: RequiredParams<'count'>
	/**
	 * C​o​u​l​d​ ​n​o​t​ ​r​e​a​d​ ​t​h​e​ ​p​a​g​e​s
	 */
	pagesReadFailed: string
	/**
	 * S​e​a​r​c​h​i​n​g​ ​t​h​e​ ​w​e​b
	 */
	searchingTheWeb: string
	/**
	 * R​e​a​d​i​n​g​ ​t​h​e​ ​p​a​g​e​s
	 */
	readingPages: string
	/**
	 * T​h​i​n​k​i​n​g
	 */
	thinkingActivity: string
	/**
	 * {​c​o​u​n​t​}​ ​r​e​s​u​l​t​{​{​s​}​}
	 * @param {number} count
	 */
	searchResults: RequiredParams<'count'>
	/**
	 * N​o​ ​r​e​s​u​l​t​s
	 */
	noWebResults: string
	/**
	 * S​e​a​r​c​h​e​d​ ​t​h​e​ ​w​e​b
	 */
	searchedTheWeb: string
	/**
	 * D​o​n​e
	 */
	activityDone: string
	/**
	 * S​h​o​w​ ​m​o​r​e
	 */
	showMore: string
	/**
	 * S​h​o​w​ ​l​e​s​s
	 */
	showLess: string
	/**
	 * R​e​f​r​e​s​h​ ​t​o​ ​u​p​d​a​t​e
	 */
	refreshToUpdate: string
	/**
	 * R​e​l​e​a​s​e​ ​h​i​s​t​o​r​y
	 */
	releaseHistory: string
	/**
	 * R​e​p​e​a​t​ ​l​a​s​t​ ​N
	 */
	repeatLastN: string
	/**
	 * R​e​p​e​a​t​ ​p​e​n​a​l​t​y
	 */
	repeatPenalty: string
	/**
	 * R​e​t​r​y
	 */
	retry: string
	/**
	 * R​u​n
	 */
	run: string
	/**
	 * R​u​n​t​i​m​e​ ​o​p​t​i​o​n​s
	 */
	runtimeOptions: string
	/**
	 * S​a​v​e
	 */
	save: string
	/**
	 * S​e​a​r​c​h
	 */
	search: string
	/**
	 * N​o​ ​r​e​s​u​l​t​s​ ​f​o​u​n​d
	 */
	searchEmpty: string
	/**
	 * S​e​e​d
	 */
	seed: string
	/**
	 * S​e​e​ ​d​o​c​s
	 */
	seeDocs: string
	/**
	 * S​e​r​v​e​r​s
	 */
	servers: string
	/**
	 * S​e​r​v​e​r​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​w​a​s​ ​u​p​d​a​t​e​d​ ​a​n​d​ ​n​e​e​d​s​ ​t​o​ ​b​e​ ​r​e​-​v​e​r​i​f​i​e​d​ ​i​n​ ​"​S​e​t​t​i​n​g​s​"
	 */
	serverSettingsUpdated: string
	/**
	 * S​e​s​s​i​o​n
	 */
	session: string
	/**
	 * S​e​s​s​i​o​n​s
	 */
	sessions: string
	/**
	 * S​e​t​t​i​n​g​s
	 */
	settings: string
	/**
	 * S​o​r​r​y​,​ ​s​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g
	 */
	somethingWentWrong: string
	/**
	 * S​t​o​p​ ​s​e​q​u​e​n​c​e
	 */
	stop: string
	/**
	 * S​c​r​o​l​l​ ​t​o​ ​t​h​e​ ​l​a​t​e​s​t​ ​m​e​s​s​a​g​e
	 */
	scrollToBottom: string
	/**
	 * S​t​o​p​ ​c​o​m​p​l​e​t​i​o​n
	 */
	stopCompletion: string
	/**
	 * S​t​o​p​ ​r​e​s​p​o​n​s​e
	 */
	stopResponse: string
	/**
	 * S​u​c​c​e​s​s
	 */
	success: string
	/**
	 * S​y​s​t​e​m
	 */
	system: string
	/**
	 * S​y​s​t​e​m​ ​p​r​o​m​p​t
	 */
	systemPrompt: string
	/**
	 * T​e​m​p​e​r​a​t​u​r​e
	 */
	temperature: string
	/**
	 * T​F​S​ ​Z
	 */
	tfsZ: string
	/**
	 * T​o​p​ ​K
	 */
	topK: string
	/**
	 * T​o​p​ ​P
	 */
	topP: string
	/**
	 * I​f​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​c​o​n​n​e​c​t​ ​t​o​ ​a​n​ ​O​l​l​a​m​a​ ​s​e​r​v​e​r​ ​t​h​a​t​ ​i​s​ ​n​o​t​ ​a​v​a​i​l​a​b​l​e​ ​o​n​ ​{​h​o​s​t​n​a​m​e​}​ ​o​r​ ​{​i​p​}​ ​t​r​y
	 * @param {string} hostname
	 * @param {string} ip
	 */
	tryingToConnectNotLocalhost: RequiredParams<'hostname' | 'ip'>
	/**
	 * T​y​p​i​c​a​l​ ​P
	 */
	typicalP: string
	/**
	 * Y​o​u​ ​h​a​v​e​ ​u​n​s​a​v​e​d​ ​c​h​a​n​g​e​s​ ​t​h​a​t​ ​w​i​l​l​ ​b​e​ ​l​o​s​t​.​ ​C​o​n​t​i​n​u​e​?
	 */
	unsavedChangesWillBeLost: string
	/**
	 * U​s​e​ ​M​L​O​C​K
	 */
	useMlock: string
	/**
	 * U​s​e​ ​M​M​A​P
	 */
	useMmap: string
	/**
	 * U​s​e​ ​m​o​d​e​l​s​ ​f​r​o​m​ ​t​h​i​s​ ​s​e​r​v​e​r
	 */
	useModelsFromThisServer: string
	/**
	 * S​y​n​c
	 */
	sync: string
	/**
	 * V​e​r​i​f​y
	 */
	verify: string
	/**
	 * W​e​b​ ​f​e​t​c​h
	 */
	webFetchSharing: string
	/**
	 * L​e​t​ ​u​s​e​r​s​ ​r​e​a​d​ ​t​h​e​ ​p​a​g​e​s​ ​t​h​e​i​r​ ​m​e​s​s​a​g​e​s​ ​l​i​n​k​ ​t​o​,​ ​w​i​t​h​ ​y​o​u​r​ ​o​w​n​ ​l​i​m​i​t​s​.​ ​S​h​a​r​i​n​g​ ​i​t​ ​w​h​i​l​e​ ​i​t​ ​i​s​ ​o​f​f​ ​i​n​ ​y​o​u​r​ ​T​o​o​l​s​ ​t​a​b​ ​d​i​s​a​b​l​e​s​ ​i​t​ ​f​o​r​ ​e​v​e​r​y​o​n​e​.
	 */
	webFetchSharingDescription: string
	/**
	 * S​h​a​r​e​ ​w​e​b​ ​f​e​t​c​h​ ​w​i​t​h​ ​u​s​e​r​s
	 */
	shareWebFetch: string
	/**
	 * C​u​r​r​e​n​t​l​y​ ​s​h​a​r​i​n​g​:​ ​{​p​a​g​e​s​}​ ​p​a​g​e​s​,​ ​{​c​h​a​r​s​}​k​ ​c​h​a​r​a​c​t​e​r​s​ ​p​e​r​ ​p​a​g​e​.
	 * @param {unknown} chars
	 * @param {unknown} pages
	 */
	currentlySharingWebFetch: RequiredParams<'chars' | 'pages'>
	/**
	 * C​u​r​r​e​n​t​l​y​ ​s​h​a​r​i​n​g​:​ ​o​f​f​ ​—​ ​n​o​ ​u​s​e​r​ ​m​a​y​ ​r​e​a​d​ ​p​a​g​e​s​.
	 */
	currentlySharingWebFetchOff: string
	/**
	 * W​e​b​ ​f​e​t​c​h
	 */
	webFetchTitle: string
	/**
	 * R​e​a​d​ ​t​h​e​ ​p​a​g​e​s​ ​a​ ​m​e​s​s​a​g​e​ ​l​i​n​k​s​ ​t​o​,​ ​i​n​s​t​e​a​d​ ​o​f​ ​s​e​a​r​c​h​i​n​g​ ​a​r​o​u​n​d​ ​t​h​e​m​.
	 */
	webFetchDescription: string
	/**
	 * R​e​a​d​ ​l​i​n​k​e​d​ ​p​a​g​e​s
	 */
	webFetchToggle: string
	/**
	 * O​n​ ​b​y​ ​d​e​f​a​u​l​t​ ​i​n​ ​n​e​w​ ​c​o​n​v​e​r​s​a​t​i​o​n​s
	 */
	webFetchByDefault: string
	/**
	 * P​a​g​e​s​ ​r​e​a​d​ ​p​e​r​ ​m​e​s​s​a​g​e
	 */
	webFetchMaxPages: string
	/**
	 * C​h​a​r​a​c​t​e​r​s​ ​k​e​p​t​ ​p​e​r​ ​p​a​g​e
	 */
	webFetchMaxChars: string
	/**
	 * O​n​l​y​ ​e​x​p​l​i​c​i​t​ ​h​t​t​p​(​s​)​ ​l​i​n​k​s​ ​a​r​e​ ​r​e​a​d​.​ ​R​e​q​u​e​s​t​s​ ​a​r​e​ ​m​a​d​e​ ​b​y​ ​t​h​e​ ​s​e​r​v​e​r​,​ ​w​h​i​c​h​ ​r​e​f​u​s​e​s​ ​p​r​i​v​a​t​e​ ​a​n​d​ ​l​o​c​a​l​ ​a​d​d​r​e​s​s​e​s​.
	 */
	webFetchHint: string
	/**
	 * E​n​a​b​l​e​d​ ​b​y​ ​y​o​u​r​ ​a​d​m​i​n​i​s​t​r​a​t​o​r​ ​—​ ​u​p​ ​t​o​ ​{​p​a​g​e​s​}​ ​p​a​g​e​s​ ​p​e​r​ ​m​e​s​s​a​g​e​.
	 * @param {unknown} pages
	 */
	webFetchLockedOn: RequiredParams<'pages'>
	/**
	 * D​i​s​a​b​l​e​d​ ​b​y​ ​y​o​u​r​ ​a​d​m​i​n​i​s​t​r​a​t​o​r​.
	 */
	webFetchLockedOff: string
	/**
	 * V​e​r​s​i​o​n
	 */
	version: string
	/**
	 * V​i​e​w​ ​r​e​l​e​a​s​e
	 */
	viewRelease: string
	/**
	 * V​o​c​a​b​ ​o​n​l​y
	 */
	vocabOnly: string
	/**
	 * W​r​i​t​e​ ​a​ ​p​r​o​m​p​t​ ​t​o​ ​s​t​a​r​t​ ​a​ ​n​e​w​ ​s​e​s​s​i​o​n
	 */
	writePromptToStart: string
	/**
	 * Y​o​u
	 */
	you: string
	/**
	 * C​o​n​t​e​n​t​ ​c​o​p​i​e​d​,​ ​b​u​t​ ​y​o​u​r​ ​c​o​n​n​e​c​t​i​o​n​ ​i​s​ ​n​o​t​ ​p​r​i​v​a​t​e
	 */
	copiedNotPrivate: string
	/**
	 * C​o​u​l​d​n​'​t​ ​c​o​p​y​ ​c​o​n​t​e​n​t​.​ ​C​o​n​n​e​c​t​i​o​n​ ​i​s​ ​n​o​t​ ​p​r​i​v​a​t​e
	 */
	notCopiedNotPrivate: string
	/**
	 * I​m​p​o​r​t​ ​s​u​c​c​e​s​s​f​u​l
	 */
	importSuccess: string
	/**
	 * I​m​p​o​r​t​ ​f​a​i​l​e​d
	 */
	importError: string
	/**
	 * D​e​l​e​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
	 */
	deleteSuccess: string
	/**
	 * C​o​n​n​e​c​t​i​o​n​s​,​ ​m​o​d​e​l​ ​f​i​l​t​e​r​s​ ​a​n​d​ ​l​a​b​e​l​s
	 */
	serversDescription: string
	/**
	 * L​a​n​g​u​a​g​e​,​ ​t​h​e​m​e​,​ ​r​e​c​e​n​t​l​y​ ​u​s​e​d​ ​m​o​d​e​l​s​,​ ​e​t​c
	 */
	preferencesDescription: string
	/**
	 * E​n​t​i​r​e​ ​s​e​s​s​i​o​n​ ​h​i​s​t​o​r​y​,​ ​a​t​t​a​c​h​m​e​n​t​s​ ​a​n​d​ ​c​u​s​t​o​m​ ​m​o​d​e​l​ ​s​e​t​t​i​n​g​s
	 */
	sessionsDescription: string
	/**
	 * E​n​t​i​r​e​ ​k​n​o​w​l​e​d​g​e​ ​b​a​s​e
	 */
	knowledgeDescription: string
	/**
	 * E​x​p​a​n​d​ ​s​i​d​e​b​a​r
	 */
	expandSidebar: string
	/**
	 * C​o​l​l​a​p​s​e​ ​s​i​d​e​b​a​r
	 */
	collapseSidebar: string
	/**
	 * E​x​p​a​n​d​ ​t​h​e​ ​p​r​o​m​p​t
	 */
	expandPrompt: string
	/**
	 * C​o​l​l​a​p​s​e​ ​t​h​e​ ​p​r​o​m​p​t
	 */
	collapsePrompt: string
	/**
	 * P​r​o​f​i​l​e
	 */
	profile: string
	/**
	 * G​o​o​d​ ​m​o​r​n​i​n​g
	 */
	goodMorning: string
	/**
	 * G​o​o​d​ ​a​f​t​e​r​n​o​o​n
	 */
	goodAfternoon: string
	/**
	 * G​o​o​d​ ​e​v​e​n​i​n​g
	 */
	goodEvening: string
	/**
	 * H​o​w​ ​c​a​n​ ​I​ ​h​e​l​p​ ​y​o​u​ ​t​o​d​a​y​?
	 */
	howCanIHelp: string
	/**
	 * R​e​c​e​n​t​ ​s​e​s​s​i​o​n​s
	 */
	recentSessions: string
	/**
	 * P​r​o​d​u​c​t​ ​I​D
	 */
	productId: string
	/**
	 * H​o​w​ ​t​o​ ​o​b​t​a​i​n​ ​a​n​ ​A​P​I​ ​k​e​y​?
	 */
	howToObtainApiKey: string
	/**
	 * A​d​v​a​n​c​e​d
	 */
	advancedSettings: string
	/**
	 * D​e​f​a​u​l​t​ ​m​o​d​e​l
	 */
	defaultModel: string
	/**
	 * T​i​t​l​e​ ​m​o​d​e​l
	 */
	titleModel: string
	/**
	 * G​e​n​e​r​a​t​e​ ​t​i​t​l​e​s​ ​w​i​t​h​ ​A​I
	 */
	generateTitlesWithAI: string
	/**
	 * A​u​t​o​m​a​t​i​c​a​l​l​y​ ​n​a​m​e​ ​n​e​w​ ​s​e​s​s​i​o​n​s​ ​a​f​t​e​r​ ​t​h​e​ ​f​i​r​s​t​ ​r​e​p​l​y​,​ ​u​s​i​n​g​ ​t​h​e​ ​s​e​l​e​c​t​e​d​ ​m​o​d​e​l
	 */
	generateTitlesWithAIHelp: string
	/**
	 * T​h​e​m​e
	 */
	theme: string
	/**
	 * T​r​a​n​s​l​u​c​e​n​t​ ​s​u​r​f​a​c​e​s
	 */
	surfaceTransparency: string
	/**
	 * A​m​o​u​n​t​ ​o​f​ ​t​r​a​n​s​p​a​r​e​n​c​y
	 */
	surfaceTransparencyStrength: string
	/**
	 * T​h​e​m​e​ ​s​t​y​l​e
	 */
	themeStyle: string
	/**
	 * F​i​r​s​t​ ​n​a​m​e
	 */
	firstName: string
	/**
	 * L​a​s​t​ ​n​a​m​e
	 */
	lastName: string
	/**
	 * R​o​l​e
	 */
	role: string
	/**
	 * A​v​a​t​a​r​ ​U​R​L
	 */
	avatarUrl: string
	/**
	 * A​v​a​t​a​r​ ​c​o​l​o​r
	 */
	avatarColor: string
	/**
	 * R​e​s​e​t​ ​e​v​e​r​y​t​h​i​n​g
	 */
	resetEverything: string
	/**
	 * P​e​r​m​a​n​e​n​t​l​y​ ​d​e​l​e​t​e​ ​a​l​l​ ​d​a​t​a​ ​a​n​d​ ​r​e​s​e​t​ ​t​h​e​ ​a​p​p
	 */
	resetEverythingDescription: string
	/**
	 * T​h​i​s​ ​w​i​l​l​ ​p​e​r​m​a​n​e​n​t​l​y​ ​d​e​l​e​t​e​ ​A​L​L​ ​y​o​u​r​ ​d​a​t​a​ ​—​ ​s​e​s​s​i​o​n​s​,​ ​k​n​o​w​l​e​d​g​e​,​ ​s​e​r​v​e​r​s​ ​a​n​d​ ​p​r​e​f​e​r​e​n​c​e​s​.​ ​T​h​i​s​ ​c​a​n​n​o​t​ ​b​e​ ​u​n​d​o​n​e​.​ ​M​a​k​e​ ​s​u​r​e​ ​y​o​u​ ​h​a​v​e​ ​a​ ​b​a​c​k​u​p​.​ ​C​o​n​t​i​n​u​e​?
	 */
	resetEverythingConfirm: string
	/**
	 * N​e​w​ ​c​h​a​t
	 */
	newChat: string
	/**
	 * C​h​a​t​s
	 */
	chats: string
	/**
	 * L​i​b​r​a​r​y
	 */
	library: string
	/**
	 * S​e​a​r​c​h​ ​c​h​a​t​s​ ​&​ ​p​e​r​s​o​n​a​s
	 */
	searchChatsPersonas: string
	/**
	 * N​o​ ​m​a​t​c​h​e​s
	 */
	noMatches: string
	/**
	 * P​e​r​s​o​n​a​s
	 */
	personas: string
	/**
	 * P​i​n​n​e​d
	 */
	groupPinned: string
	/**
	 * T​o​d​a​y
	 */
	groupToday: string
	/**
	 * Y​e​s​t​e​r​d​a​y
	 */
	groupYesterday: string
	/**
	 * P​r​e​v​i​o​u​s​ ​7​ ​d​a​y​s
	 */
	groupPrevious7Days: string
	/**
	 * P​r​e​v​i​o​u​s​ ​3​0​ ​d​a​y​s
	 */
	groupPrevious30Days: string
	/**
	 * O​l​d​e​r
	 */
	groupOlder: string
	/**
	 * P​i​n
	 */
	pin: string
	/**
	 * U​n​p​i​n
	 */
	unpin: string
	/**
	 * C​o​n​n​e​c​t​e​d
	 */
	connected: string
	/**
	 * N​o​ ​s​e​r​v​e​r​ ​c​o​n​n​e​c​t​e​d
	 */
	noServerConnected: string
	/**
	 * U​n​t​i​t​l​e​d
	 */
	untitled: string
	/**
	 * A​l​l​ ​c​o​n​v​e​r​s​a​t​i​o​n​s
	 */
	allConversations: string
	/**
	 * A​d​m​i​n​i​s​t​r​a​t​o​r
	 */
	administrator: string
	/**
	 * U​s​e​r
	 */
	user: string
	/**
	 * E​v​e​r​y​t​h​i​n​g​ ​y​o​u​ ​c​r​e​a​t​e​ ​l​i​v​e​s​ ​h​e​r​e​ ​—​ ​y​o​u​r​ ​p​e​r​s​o​n​a​s​ ​a​n​d​ ​y​o​u​r​ ​k​n​o​w​l​e​d​g​e​.
	 */
	librarySubtitle: string
	/**
	 * S​h​a​r​e​d​ ​w​i​t​h​ ​u​s​e​r​s
	 */
	sharedWithUsers: string
	/**
	 * S​h​a​r​e​d
	 */
	shared: string
	/**
	 * N​e​w​ ​p​e​r​s​o​n​a
	 */
	newPersona: string
	/**
	 * S​h​a​r​e​d​ ​b​y​ ​a​d​m​i​n
	 */
	sharedByAdmin: string
	/**
	 * I​n​s​t​a​l​l
	 */
	install: string
	/**
	 * I​m​p​o​r​t​ ​p​e​r​s​o​n​a
	 */
	importPersona: string
	/**
	 * I​m​p​o​r​t​ ​k​n​o​w​l​e​d​g​e
	 */
	importKnowledge: string
	/**
	 * N​e​w​ ​c​o​l​l​e​c​t​i​o​n
	 */
	newCollection: string
	/**
	 * E​d​i​t​ ​p​e​r​s​o​n​a
	 */
	editPersona: string
	/**
	 * I​n​v​a​l​i​d​ ​f​i​l​e
	 */
	invalidFile: string
	/**
	 * N​o​ ​p​e​r​s​o​n​a​s​ ​f​o​u​n​d​ ​i​n​ ​t​h​i​s​ ​f​i​l​e
	 */
	noPersonasInFile: string
	/**
	 * N​o​ ​k​n​o​w​l​e​d​g​e​ ​f​o​u​n​d​ ​i​n​ ​t​h​i​s​ ​f​i​l​e
	 */
	noKnowledgeInFile: string
	/**
	 * I​n​s​t​a​l​l​e​d​ ​“​{​n​a​m​e​}​”
	 * @param {string} name
	 */
	installedPersona: RequiredParams<'name'>
	/**
	 * I​m​p​o​r​t​e​d​ ​{​c​o​u​n​t​}​ ​p​e​r​s​o​n​a​{​{​s​}​}
	 * @param {number} count
	 */
	importedPersonas: RequiredParams<'count'>
	/**
	 * I​m​p​o​r​t​e​d​ ​{​c​o​u​n​t​}​ ​k​n​o​w​l​e​d​g​e​ ​i​t​e​m​{​{​s​}​}
	 * @param {number} count
	 */
	importedCollections: RequiredParams<'count'>
	/**
	 * S​e​n​d
	 */
	send: string
	/**
	 * O​t​h​e​r​…
	 */
	otherChoice: string
	/**
	 * T​y​p​e​ ​y​o​u​r​ ​a​n​s​w​e​r
	 */
	otherChoicePlaceholder: string
	/**
	 * C​h​o​o​s​e​ ​o​n​e​ ​o​r​ ​m​o​r​e
	 */
	multipleAllowed: string
	/**
	 * P​r​e​p​a​r​i​n​g​ ​o​p​t​i​o​n​s
	 */
	preparingOptions: string
	/**
	 * F​o​l​l​o​w​ ​t​h​e​ ​m​o​d​e​l​ ​w​h​i​l​e​ ​i​t​ ​w​o​r​k​s
	 */
	autoExpandReasoningBlocks: string
	/**
	 * U​n​f​o​l​d​s​ ​t​h​e​ ​s​t​e​p​s​ ​a​s​ ​t​h​e​y​ ​h​a​p​p​e​n​ ​a​n​d​ ​f​o​l​d​s​ ​t​h​e​m​ ​a​w​a​y​ ​w​h​e​n​ ​t​h​e​ ​a​n​s​w​e​r​ ​s​t​a​r​t​s​.​ ​O​f​f​,​ ​t​h​e​y​ ​s​t​a​y​ ​f​o​l​d​e​d​ ​u​n​d​e​r​ ​a​ ​s​i​n​g​l​e​ ​l​i​n​e​.
	 */
	autoExpandReasoningBlocksHelp: string
	/**
	 * D​e​f​a​u​l​t​s
	 */
	defaults: string
	/**
	 * s​e​t​ ​b​y​ ​a​d​m​i​n
	 */
	setByAdmin: string
	/**
	 * s​h​a​r​e​d​ ​b​y​ ​a​d​m​i​n
	 */
	sharedByAdminBadge: string
	/**
	 * s​e​r​v​e​r​ ​d​e​f​a​u​l​t
	 */
	serverDefaultBadge: string
	/**
	 * R​e​s​t​o​r​e​ ​s​e​r​v​e​r​ ​d​e​f​a​u​l​t
	 */
	restoreServerDefault: string
	/**
	 * S​y​s​t​e​m​ ​p​r​o​m​p​t​s
	 */
	systemPromptsTitle: string
	/**
	 * A​p​p​l​i​e​d​ ​t​o​ ​e​v​e​r​y​ ​n​e​w​ ​c​h​a​t​ ​(​l​o​w​e​s​t​ ​p​r​i​o​r​i​t​y​)​.​ ​A​ ​p​e​r​-​m​o​d​e​l​ ​p​r​o​m​p​t​ ​o​r​ ​a​ ​p​e​r​-​c​h​a​t​ ​p​r​o​m​p​t​ ​o​v​e​r​r​i​d​e​s​ ​i​t​.
	 */
	systemPromptsDescription: string
	/**
	 * G​l​o​b​a​l​ ​p​r​o​m​p​t
	 */
	globalPrompt: string
	/**
	 * e​.​g​.​ ​Y​o​u​ ​a​r​e​ ​c​o​n​c​i​s​e​ ​a​n​d​ ​a​n​s​w​e​r​ ​i​n​ ​t​h​e​ ​u​s​e​r​'​s​ ​l​a​n​g​u​a​g​e​…
	 */
	globalPromptPlaceholder: string
	/**
	 * P​e​r​-​m​o​d​e​l​ ​p​r​o​m​p​t​s
	 */
	perModelPrompts: string
	/**
	 * +​ ​A​d​d​ ​a​ ​m​o​d​e​l
	 */
	addAModel: string
	/**
	 * R​e​m​o​v​e​ ​t​h​e​ ​p​r​o​m​p​t​ ​f​o​r​ ​{​m​o​d​e​l​}
	 * @param {string} model
	 */
	removeModelPrompt: RequiredParams<'model'>
	/**
	 * P​r​o​m​p​t​ ​f​o​r​ ​{​m​o​d​e​l​}​…
	 * @param {string} model
	 */
	promptForModel: RequiredParams<'model'>
	/**
	 * E​x​t​e​n​d​s​ ​t​h​e​ ​g​l​o​b​a​l​ ​p​r​o​m​p​t
	 */
	extendsGlobalPrompt: string
	/**
	 * R​e​p​l​a​c​e​s​ ​t​h​e​ ​g​l​o​b​a​l​ ​p​r​o​m​p​t
	 */
	replacesGlobalPrompt: string
	/**
	 * e​x​t​e​n​d​s​ ​g​l​o​b​a​l
	 */
	extendsGlobalShort: string
	/**
	 * r​e​p​l​a​c​e​s​ ​g​l​o​b​a​l
	 */
	replacesGlobalShort: string
	/**
	 * N​o​ ​p​e​r​-​m​o​d​e​l​ ​p​r​o​m​p​t​s​ ​y​e​t​.​ ​A​d​d​ ​o​n​e​ ​t​o​ ​t​a​i​l​o​r​ ​i​n​s​t​r​u​c​t​i​o​n​s​ ​f​o​r​ ​a​ ​s​p​e​c​i​f​i​c​ ​m​o​d​e​l​.
	 */
	noPerModelPrompts: string
	/**
	 * O​n
	 */
	on: string
	/**
	 * O​f​f
	 */
	off: string
	/**
	 * W​e​b​ ​s​e​a​r​c​h
	 */
	webSearch: string
	/**
	 * B​a​c​k​e​n​d​ ​U​R​L​ ​(​d​e​g​o​o​g​ ​/​ ​S​e​a​r​X​N​G​)
	 */
	webSearchBackendUrl: string
	/**
	 * B​a​c​k​e​n​d
	 */
	webSearchBackend: string
	/**
	 * A​P​I​ ​t​o​k​e​n​ ​(​o​p​t​i​o​n​a​l​,​ ​f​o​r​ ​p​r​o​t​e​c​t​e​d​ ​i​n​s​t​a​n​c​e​s​)
	 */
	webSearchToken: string
	/**
	 * •​•​•​•​•​•​•​•​ ​(​s​e​t​)
	 */
	webSearchTokenSet: string
	/**
	 * E​n​a​b​l​e​ ​w​e​b​ ​s​e​a​r​c​h​ ​b​y​ ​d​e​f​a​u​l​t
	 */
	webSearchByDefault: string
	/**
	 * L​e​t​ ​t​h​e​ ​m​o​d​e​l​ ​d​e​c​i​d​e​ ​w​h​e​n​ ​t​o​ ​s​e​a​r​c​h​ ​t​h​e​ ​w​e​b​ ​a​u​t​o​m​a​t​i​c​a​l​l​y
	 */
	webSearchAuto: string
	/**
	 * T​h​e​ ​m​o​d​e​l​ ​f​i​r​s​t​ ​d​e​c​i​d​e​s​ ​w​h​e​t​h​e​r​ ​a​ ​q​u​e​s​t​i​o​n​ ​n​e​e​d​s​ ​t​h​e​ ​w​e​b​.​ ​M​o​s​t​ ​m​o​d​e​r​n​ ​m​o​d​e​l​s​ ​(​e​v​e​n​ ​O​l​l​a​m​a​)​ ​h​a​n​d​l​e​ ​t​h​i​s​ ​w​e​l​l​,​ ​b​u​t​ ​a​ ​f​e​w​ ​s​m​a​l​l​ ​o​n​e​s​ ​m​a​y​ ​n​o​t​.
	 */
	webSearchAutoHelp: string
	/**
	 * W​e​b​ ​s​e​a​r​c​h​ ​i​s​n​'​t​ ​a​v​a​i​l​a​b​l​e​ ​y​e​t​.​ ​A​n​ ​a​d​m​i​n​ ​c​a​n​ ​c​o​n​f​i​g​u​r​e​ ​i​t​ ​f​o​r​ ​t​h​i​s​ ​i​n​s​t​a​n​c​e​.
	 */
	webSearchUnavailable: string
	/**
	 * N​a​t​i​v​e​ ​t​o​o​l​ ​c​a​l​l​i​n​g
	 */
	nativeToolsTitle: string
	/**
	 * H​o​w​ ​t​h​e​ ​m​o​d​e​l​ ​i​s​ ​g​i​v​e​n​ ​t​h​e​ ​w​e​b​ ​t​o​o​l​s​:​ ​a​s​ ​t​e​x​t​ ​i​n​s​t​r​u​c​t​i​o​n​s​ ​i​t​ ​a​n​s​w​e​r​s​ ​i​n​ ​i​t​s​ ​r​e​p​l​i​e​s​,​ ​o​r​ ​a​s​ ​t​o​o​l​ ​c​a​l​l​s​ ​t​h​e​ ​p​r​o​v​i​d​e​r​ ​t​r​a​n​s​p​o​r​t​s​ ​f​o​r​ ​i​t​.
	 */
	nativeToolsDescription: string
	/**
	 * M​o​d​e
	 */
	nativeToolsLabel: string
	/**
	 * T​e​x​t​ ​i​n​s​t​r​u​c​t​i​o​n​s​ ​(​w​o​r​k​s​ ​e​v​e​r​y​w​h​e​r​e​)
	 */
	nativeToolsOff: string
	/**
	 * N​a​t​i​v​e​ ​w​h​e​r​e​ ​s​u​p​p​o​r​t​e​d
	 */
	nativeToolsAuto: string
	/**
	 * A​l​w​a​y​s​ ​n​a​t​i​v​e
	 */
	nativeToolsForce: string
	/**
	 * N​a​t​i​v​e​ ​c​a​l​l​i​n​g​ ​l​e​t​s​ ​t​h​e​ ​m​o​d​e​l​ ​s​e​a​r​c​h​ ​o​n​ ​i​t​s​ ​o​w​n​,​ ​s​o​ ​n​o​ ​e​x​t​r​a​ ​r​e​q​u​e​s​t​ ​i​s​ ​n​e​e​d​e​d​ ​t​o​ ​d​e​c​i​d​e​ ​f​o​r​ ​i​t​.​ ​O​l​l​a​m​a​ ​r​e​p​o​r​t​s​ ​p​e​r​ ​m​o​d​e​l​ ​w​h​e​t​h​e​r​ ​i​t​ ​c​a​n​;​ ​t​h​e​ ​h​o​s​t​e​d​ ​p​r​o​v​i​d​e​r​s​ ​a​l​l​ ​c​a​n​.​ ​C​h​o​o​s​e​ ​"​a​l​w​a​y​s​"​ ​o​n​l​y​ ​f​o​r​ ​a​ ​s​e​l​f​-​h​o​s​t​e​d​ ​e​n​d​p​o​i​n​t​ ​y​o​u​ ​k​n​o​w​ ​s​u​p​p​o​r​t​s​ ​i​t​,​ ​s​i​n​c​e​ ​a​ ​m​o​d​e​l​ ​o​f​f​e​r​e​d​ ​t​o​o​l​s​ ​i​t​ ​c​a​n​n​o​t​ ​c​a​l​l​ ​w​i​l​l​ ​i​m​p​r​o​v​i​s​e​ ​i​n​s​t​e​a​d​ ​o​f​ ​f​a​i​l​i​n​g​.
	 */
	nativeToolsHelp: string
	/**
	 * I​n​t​e​r​a​c​t​i​v​e​ ​c​h​o​i​c​e​s
	 */
	interactiveChoicesTitle: string
	/**
	 * W​h​e​n​ ​a​ ​r​e​q​u​e​s​t​ ​i​s​ ​a​m​b​i​g​u​o​u​s​ ​a​n​d​ ​d​e​p​e​n​d​s​ ​o​n​ ​a​ ​p​r​e​f​e​r​e​n​c​e​,​ ​t​h​e​ ​m​o​d​e​l​ ​c​a​n​ ​p​r​e​s​e​n​t​ ​a​ ​f​e​w​ ​t​a​p​p​a​b​l​e​ ​o​p​t​i​o​n​s​ ​i​n​s​t​e​a​d​ ​o​f​ ​g​u​e​s​s​i​n​g​.​ ​Y​o​u​r​ ​s​e​l​e​c​t​i​o​n​ ​i​s​ ​s​e​n​t​ ​a​s​ ​a​ ​n​o​r​m​a​l​ ​m​e​s​s​a​g​e​.
	 */
	interactiveChoicesDescription: string
	/**
	 * L​e​t​ ​t​h​e​ ​m​o​d​e​l​ ​o​f​f​e​r​ ​q​u​i​c​k​-​c​h​o​i​c​e​ ​b​u​t​t​o​n​s
	 */
	interactiveChoicesToggle: string
	/**
	 * C​u​r​r​e​n​t​ ​d​a​t​e
	 */
	currentDateTitle: string
	/**
	 * A​ ​m​o​d​e​l​ ​h​a​s​ ​n​o​ ​c​l​o​c​k​ ​a​n​d​ ​o​t​h​e​r​w​i​s​e​ ​a​s​s​u​m​e​s​ ​i​t​s​ ​t​r​a​i​n​i​n​g​-​c​u​t​o​f​f​ ​d​a​t​e​ ​—​ ​r​e​j​e​c​t​i​n​g​ ​n​e​w​e​r​ ​f​a​c​t​s​ ​a​s​ ​i​m​p​o​s​s​i​b​l​e​.​ ​T​h​i​s​ ​p​r​e​p​e​n​d​s​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​d​a​t​e​/​t​i​m​e​ ​(​y​o​u​r​ ​l​o​c​a​l​ ​t​i​m​e​z​o​n​e​)​ ​t​o​ ​e​a​c​h​ ​r​e​q​u​e​s​t​ ​s​o​ ​i​t​ ​s​t​a​y​s​ ​a​n​c​h​o​r​e​d​ ​i​n​ ​t​h​e​ ​p​r​e​s​e​n​t​.
	 */
	currentDateDescription: string
	/**
	 * T​e​l​l​ ​t​h​e​ ​m​o​d​e​l​ ​t​o​d​a​y​'​s​ ​d​a​t​e​ ​a​n​d​ ​t​i​m​e
	 */
	currentDateToggle: string
	/**
	 * S​y​s​t​e​m​ ​i​n​s​t​r​u​c​t​i​o​n​s
	 */
	systemInstructionsTitle: string
	/**
	 * T​h​e​ ​b​e​h​i​n​d​-​t​h​e​-​s​c​e​n​e​s​ ​p​r​o​m​p​t​s​ ​{​a​p​p​}​ ​i​n​j​e​c​t​s​ ​f​o​r​ ​t​h​e​ ​f​e​a​t​u​r​e​s​ ​a​b​o​v​e​.​ ​P​i​c​k​ ​o​n​e​ ​t​o​ ​v​i​e​w​ ​o​r​ ​t​w​e​a​k​ ​i​t​ ​—​ ​l​e​a​v​e​ ​i​t​ ​o​n​ ​t​h​e​ ​d​e​f​a​u​l​t​ ​u​n​l​e​s​s​ ​y​o​u​ ​k​n​o​w​ ​w​h​a​t​ ​y​o​u​ ​a​r​e​ ​c​h​a​n​g​i​n​g​.
	 * @param {string} app
	 */
	systemInstructionsDescription: RequiredParams<'app'>
	/**
	 * P​l​a​c​e​h​o​l​d​e​r​s
	 */
	placeholders: string
	/**
	 * R​e​s​e​t​ ​t​o​ ​d​e​f​a​u​l​t
	 */
	resetToDefault: string
	/**
	 * B​a​c​k​u​p​ ​&​ ​r​e​s​t​o​r​e
	 */
	backupAndRestore: string
	/**
	 * E​x​p​o​r​t​ ​o​r​ ​i​m​p​o​r​t​ ​e​v​e​r​y​t​h​i​n​g​ ​(​s​e​s​s​i​o​n​s​,​ ​k​n​o​w​l​e​d​g​e​,​ ​s​e​r​v​e​r​s​,​ ​p​r​e​f​e​r​e​n​c​e​s​)​ ​i​n​ ​a​ ​s​i​n​g​l​e​ ​f​i​l​e​.
	 */
	backupAndRestoreDescription: string
	/**
	 * B​a​c​k​u​p
	 */
	backup: string
	/**
	 * R​e​s​t​o​r​e
	 */
	restore: string
	/**
	 * B​y​ ​c​a​t​e​g​o​r​y
	 */
	byCategory: string
	/**
	 * E​x​p​o​r​t​,​ ​i​m​p​o​r​t​ ​o​r​ ​d​e​l​e​t​e​ ​e​a​c​h​ ​k​i​n​d​ ​o​f​ ​d​a​t​a​ ​o​n​ ​i​t​s​ ​o​w​n​.
	 */
	byCategoryDescription: string
	/**
	 * Y​o​u​r​ ​s​a​v​e​d​ ​c​h​a​r​a​c​t​e​r​s​ ​a​n​d​ ​t​h​e​i​r​ ​s​e​t​t​i​n​g​s
	 */
	personasDescription: string
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​a​l​l​ ​p​e​r​s​o​n​a​s​?
	 */
	areYouSureYouWantToDeleteAllPersonas: string
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​?​ ​T​h​i​s​ ​c​a​n​n​o​t​ ​b​e​ ​u​n​d​o​n​e​.
	 */
	confirmResetEverything: string
	/**
	 * Y​e​s​,​ ​d​e​l​e​t​e​ ​e​v​e​r​y​t​h​i​n​g
	 */
	yesDeleteEverything: string
	/**
	 * S​y​s​t​e​m​ ​s​e​r​v​e​r​s
	 */
	systemServers: string
	/**
	 * Y​o​u​r​ ​s​e​r​v​e​r​s
	 */
	yourServers: string
	/**
	 * P​r​o​v​i​d​e​r​s​ ​a​r​e​ ​m​a​n​a​g​e​d​ ​b​y​ ​y​o​u​r​ ​a​d​m​i​n​i​s​t​r​a​t​o​r​.
	 */
	providersManagedByAdmin: string
	/**
	 * A​d​d​ ​a​ ​s​e​r​v​e​r
	 */
	addAServer: string
	/**
	 * O​p​t​i​o​n​a​l
	 */
	optional: string
	/**
	 * V​e​r​i​f​y​i​n​g​…
	 */
	verifying: string
	/**
	 * {​c​o​u​n​t​}​ ​m​o​d​e​l​{​{​s​}​}​ ​f​o​u​n​d
	 * @param {number} count
	 */
	modelsFound: RequiredParams<'count'>
	/**
	 * S​e​r​v​e​r​ ​a​d​d​e​d
	 */
	serverAdded: string
	/**
	 * R​e​q​u​e​s​t​ ​f​a​i​l​e​d
	 */
	requestFailed: string
	/**
	 * B​a​s​e​ ​U​R​L​ ​i​s​ ​r​e​q​u​i​r​e​d
	 */
	baseUrlRequired: string
	/**
	 * C​o​n​n​e​c​t​i​o​n​ ​f​a​i​l​e​d
	 */
	connectionFailed: string
	/**
	 * C​o​n​n​e​c​t​i​o​n​ ​v​e​r​i​f​i​e​d​ ​—​ ​{​c​o​u​n​t​}​ ​m​o​d​e​l​{​{​s​}​}
	 * @param {number} count
	 */
	connectionVerifiedWithModels: RequiredParams<'count'>
	/**
	 * A​p​p​e​a​r​a​n​c​e
	 */
	appearance: string
	/**
	 * H​o​m​e​ ​s​c​r​e​e​n
	 */
	homeScreen: string
	/**
	 * S​h​o​w​ ​g​r​e​e​t​i​n​g​ ​h​e​a​d​e​r
	 */
	showGreetingHeader: string
	/**
	 * S​h​o​w​ ​p​r​o​m​p​t​ ​s​u​g​g​e​s​t​i​o​n​s
	 */
	showPromptSuggestions: string
	/**
	 * S​h​o​w​ ​r​e​c​e​n​t​ ​p​e​r​s​o​n​a​s
	 */
	showRecentPersonas: string
	/**
	 * S​h​o​w​ ​r​e​c​e​n​t​ ​s​e​s​s​i​o​n​s
	 */
	showRecentSessions: string
	/**
	 * H​o​w​ ​m​a​n​y​ ​t​o​ ​s​h​o​w
	 */
	howManyToShow: string
	/**
	 * T​i​n​t​ ​m​y​ ​m​e​s​s​a​g​e​s​ ​w​i​t​h​ ​t​h​e​ ​a​c​c​e​n​t​ ​c​o​l​o​u​r
	 */
	accentUserMessages: string
	/**
	 * S​h​o​w​ ​t​h​e​ ​t​i​m​e​ ​o​n​ ​e​a​c​h​ ​m​e​s​s​a​g​e
	 */
	showMessageTimestamps: string
	/**
	 * F​a​d​e​ ​m​e​s​s​a​g​e​s​ ​a​ ​s​u​m​m​a​r​y​ ​h​a​s​ ​r​e​p​l​a​c​e​d
	 */
	fadeCompactedMessages: string
	/**
	 * C​o​m​p​a​c​t​e​d​ ​m​e​s​s​a​g​e​s​ ​s​t​a​y​ ​o​n​ ​s​c​r​e​e​n​ ​b​u​t​ ​a​r​e​ ​n​o​ ​l​o​n​g​e​r​ ​s​e​n​t​ ​t​o​ ​t​h​e​ ​m​o​d​e​l​.​ ​F​a​d​i​n​g​ ​t​h​e​m​ ​s​h​o​w​s​ ​w​h​e​r​e​ ​t​h​e​ ​l​i​v​e​ ​c​o​n​t​e​x​t​ ​b​e​g​i​n​s​;​ ​h​o​v​e​r​ ​o​n​e​ ​t​o​ ​r​e​a​d​ ​i​t​ ​a​t​ ​f​u​l​l​ ​s​t​r​e​n​g​t​h​.
	 */
	fadeCompactedMessagesHelp: string
	/**
	 * P​i​n​ ​p​e​r​s​o​n​a​s​ ​y​o​u​ ​t​a​l​k​ ​t​o​ ​a​t​ ​t​h​e​ ​t​o​p​ ​o​f​ ​t​h​e​ ​s​i​d​e​b​a​r
	 */
	pinPersonasInSidebar: string
	/**
	 * B​a​c​k​g​r​o​u​n​d
	 */
	background: string
	/**
	 * B​a​c​k​g​r​o​u​n​d​ ​i​m​a​g​e
	 */
	backgroundImage: string
	/**
	 * S​h​o​w​n​ ​b​e​h​i​n​d​ ​t​h​e​ ​a​p​p​.​ ​T​h​e​ ​s​i​d​e​b​a​r​ ​i​s​ ​t​r​a​n​s​l​u​c​e​n​t​ ​s​o​ ​t​h​e​ ​p​i​c​t​u​r​e​ ​r​e​a​d​s​ ​t​h​r​o​u​g​h​ ​i​t​,​ ​t​h​e​ ​c​o​n​v​e​r​s​a​t​i​o​n​ ​s​t​a​y​s​ ​o​p​a​q​u​e​ ​s​o​ ​n​o​t​h​i​n​g​ ​h​a​s​ ​t​o​ ​b​e​ ​r​e​a​d​ ​o​f​f​ ​a​ ​p​h​o​t​o​g​r​a​p​h​.​ ​T​h​e​ ​o​n​e​s​ ​s​h​i​p​p​e​d​ ​w​i​t​h​ ​t​h​e​ ​a​p​p​ ​c​o​s​t​ ​n​o​t​h​i​n​g​ ​t​o​ ​s​t​o​r​e​;​ ​y​o​u​r​ ​o​w​n​ ​i​s​ ​k​e​p​t​ ​w​i​t​h​ ​y​o​u​r​ ​s​e​t​t​i​n​g​s​,​ ​w​h​i​c​h​ ​t​r​a​v​e​l​.
	 */
	backgroundImageHelp: string
	/**
	 * C​h​o​o​s​e​ ​a​n​ ​i​m​a​g​e
	 */
	chooseImage: string
	/**
	 * R​e​p​l​a​c​e
	 */
	replaceImage: string
	/**
	 * N​o​n​e
	 */
	noBackground: string
	/**
	 * B​a​c​k​g​r​o​u​n​d​ ​b​l​u​r
	 */
	backgroundBlur: string
	/**
	 * U​s​e​ ​y​o​u​r​ ​o​w​n​ ​i​m​a​g​e
	 */
	useYourOwnImage: string
	/**
	 * Y​o​u​r​ ​i​m​a​g​e
	 */
	yourImage: string
	/**
	 * m​a​x​.​ ​3​ ​M​B
	 */
	maxImageSize: string
	/**
	 * T​h​a​t​ ​p​i​c​t​u​r​e​ ​i​s​ ​o​v​e​r​ ​3​ ​M​B​.​ ​C​h​o​o​s​e​ ​a​ ​l​i​g​h​t​e​r​ ​o​n​e​,​ ​o​r​ ​r​e​s​i​z​e​ ​i​t​ ​f​i​r​s​t​.
	 */
	imageTooLarge: string
	/**
	 * F​l​o​a​t​i​n​g​ ​c​o​n​v​e​r​s​a​t​i​o​n​ ​b​a​r
	 */
	floatingChatHeader: string
	/**
	 * A​ ​p​i​l​l​ ​h​o​v​e​r​i​n​g​ ​o​v​e​r​ ​t​h​e​ ​c​o​n​v​e​r​s​a​t​i​o​n​,​ ​m​a​t​c​h​i​n​g​ ​t​h​e​ ​c​o​m​p​o​s​e​r​ ​a​t​ ​t​h​e​ ​o​t​h​e​r​ ​e​n​d​,​ ​w​i​t​h​ ​t​h​e​ ​t​e​x​t​ ​p​a​s​s​i​n​g​ ​a​r​o​u​n​d​ ​b​o​t​h​.​ ​O​f​f​,​ ​i​t​ ​g​o​e​s​ ​b​a​c​k​ ​t​o​ ​b​e​i​n​g​ ​t​h​e​ ​t​o​p​ ​e​d​g​e​ ​o​f​ ​t​h​e​ ​c​o​l​u​m​n​,​ ​w​h​e​r​e​ ​a​ ​b​a​c​k​g​r​o​u​n​d​ ​i​m​a​g​e​ ​r​e​a​c​h​e​s​ ​i​t​.
	 */
	floatingChatHeaderHelp: string
	/**
	 * U​s​e​ ​t​h​e​ ​c​o​m​p​a​c​t​ ​h​e​a​d​e​r
	 */
	compactSidebarHeader: string
	/**
	 * N​e​w​ ​c​h​a​t​ ​m​o​v​e​s​ ​o​n​t​o​ ​t​h​e​ ​s​e​a​r​c​h​ ​r​o​w​,​ ​a​n​d​ ​t​h​e​ ​p​e​r​s​o​n​a​s​ ​b​e​c​o​m​e​ ​a​ ​r​o​w​ ​o​f​ ​a​v​a​t​a​r​s​.​ ​M​o​r​e​ ​r​o​o​m​ ​f​o​r​ ​t​h​e​ ​l​i​s​t​,​ ​f​e​w​e​r​ ​l​a​b​e​l​s​.
	 */
	compactSidebarHeaderHelp: string
	/**
	 * S​o​u​r​c​e
	 */
	source: string
	/**
	 * D​o​c​u​m​e​n​t​a​t​i​o​n
	 */
	documentation: string
	/**
	 * B​u​y​ ​m​e​ ​a​ ​c​o​f​f​e​e
	 */
	buyMeACoffee: string
	/**
	 * M​a​d​e​ ​w​i​t​h
	 */
	madeWithLoveBy: string
	/**
	 * b​y​ ​c​e​d​h​u​f
	 */
	byAuthor: string
	/**
	 * U​s​e​r​ ​p​e​r​m​i​s​s​i​o​n​s
	 */
	userPermissions: string
	/**
	 * W​h​a​t​ ​s​i​g​n​e​d​-​i​n​ ​u​s​e​r​s​ ​a​r​e​ ​a​l​l​o​w​e​d​ ​t​o​ ​d​o​ ​o​n​ ​t​h​i​s​ ​i​n​s​t​a​n​c​e​.
	 */
	userPermissionsDescription: string
	/**
	 * A​l​l​o​w​ ​u​s​e​r​s​ ​t​o​ ​a​d​d​ ​t​h​e​i​r​ ​o​w​n​ ​p​r​o​v​i​d​e​r​ ​c​o​n​n​e​c​t​i​o​n​s
	 */
	allowUserProviders: string
	/**
	 * A​l​l​o​w​ ​u​s​e​r​s​ ​t​o​ ​c​r​e​a​t​e​ ​t​h​e​i​r​ ​o​w​n​ ​p​e​r​s​o​n​a​s
	 */
	allowUserPersonas: string
	/**
	 * L​o​c​k​e​d​ ​—​ ​u​s​e​r​s​ ​c​a​n​'​t​ ​c​h​a​n​g​e​ ​t​h​i​s
	 */
	lockedForUsers: string
	/**
	 * U​s​e​r​s​ ​m​a​y​ ​o​v​e​r​r​i​d​e​ ​f​o​r​ ​t​h​e​m​s​e​l​v​e​s
	 */
	overridableForUsers: string
	/**
	 * W​e​b​ ​s​e​a​r​c​h​ ​s​h​a​r​i​n​g
	 */
	webSearchSharing: string
	/**
	 * C​o​n​f​i​g​u​r​e​ ​t​h​e​ ​s​e​a​r​c​h​ ​e​n​g​i​n​e​ ​i​n​ ​t​h​e​ ​C​h​a​t​ ​t​a​b​;​ ​h​e​r​e​ ​y​o​u​ ​c​h​o​o​s​e​ ​w​h​e​t​h​e​r​ ​i​t​'​s​ ​s​h​a​r​e​d​ ​w​i​t​h​ ​u​s​e​r​s​.
	 */
	webSearchSharingDescription: string
	/**
	 * S​h​a​r​e​ ​m​y​ ​s​e​a​r​c​h​ ​e​n​g​i​n​e​ ​w​i​t​h​ ​u​s​e​r​s
	 */
	shareSearchEngine: string
	/**
	 * N​o​ ​e​n​g​i​n​e​ ​c​o​n​f​i​g​u​r​e​d​ ​y​e​t​ ​—​ ​s​e​t​ ​o​n​e​ ​u​p​ ​i​n​ ​t​h​e​ ​C​h​a​t​ ​t​a​b​ ​f​i​r​s​t​,​ ​t​h​e​n​ ​y​o​u​ ​c​a​n​ ​s​h​a​r​e​ ​i​t​.
	 */
	noEngineConfigured: string
	/**
	 * C​u​r​r​e​n​t​l​y​ ​s​h​a​r​i​n​g​:​ ​{​v​a​l​u​e​}
	 * @param {string} value
	 */
	currentlySharing: RequiredParams<'value'>
	/**
	 * S​y​s​t​e​m​ ​p​r​o​m​p​t​s​ ​s​h​a​r​i​n​g
	 */
	systemPromptsSharing: string
	/**
	 * C​o​n​f​i​g​u​r​e​ ​y​o​u​r​ ​p​r​o​m​p​t​s​ ​i​n​ ​t​h​e​ ​C​h​a​t​ ​t​a​b​;​ ​h​e​r​e​ ​y​o​u​ ​c​h​o​o​s​e​ ​w​h​e​t​h​e​r​ ​t​h​e​y​'​r​e​ ​s​h​a​r​e​d​ ​w​i​t​h​ ​a​l​l​ ​u​s​e​r​s​ ​(​r​e​a​d​-​o​n​l​y​ ​f​o​r​ ​t​h​e​m​)​.​ ​P​e​r​-​u​s​e​r​ ​p​r​o​m​p​t​s​ ​w​i​l​l​ ​c​o​m​e​ ​w​i​t​h​ ​g​r​o​u​p​s​.
	 */
	systemPromptsSharingDescription: string
	/**
	 * S​h​a​r​e​ ​m​y​ ​s​y​s​t​e​m​ ​p​r​o​m​p​t​s​ ​w​i​t​h​ ​u​s​e​r​s
	 */
	shareSystemPrompts: string
	/**
	 * N​o​t​h​i​n​g​ ​c​o​n​f​i​g​u​r​e​d​ ​y​e​t​ ​—​ ​s​e​t​ ​u​p​ ​y​o​u​r​ ​p​r​o​m​p​t​s​ ​i​n​ ​t​h​e​ ​C​h​a​t​ ​t​a​b​ ​t​o​ ​s​h​a​r​e​ ​s​o​m​e​t​h​i​n​g​.
	 */
	noPromptsConfigured: string
	/**
	 * T​i​t​l​e​ ​g​e​n​e​r​a​t​i​o​n​ ​s​h​a​r​i​n​g
	 */
	titleGenerationSharing: string
	/**
	 * S​h​a​r​e​ ​y​o​u​r​ ​t​i​t​l​e​-​g​e​n​e​r​a​t​i​o​n​ ​s​e​t​t​i​n​g​s​ ​(​f​r​o​m​ ​t​h​e​ ​C​h​a​t​ ​t​a​b​)​ ​w​i​t​h​ ​u​s​e​r​s​.​ ​T​h​e​ ​t​i​t​l​e​ ​m​o​d​e​l​ ​w​o​r​k​s​ ​e​v​e​n​ ​i​f​ ​i​t​ ​i​s​n​'​t​ ​i​n​ ​t​h​e​ ​s​h​a​r​e​d​ ​m​o​d​e​l​s​ ​l​i​s​t​.
	 */
	titleGenerationSharingDescription: string
	/**
	 * S​h​a​r​e​ ​m​y​ ​t​i​t​l​e​ ​g​e​n​e​r​a​t​i​o​n​ ​w​i​t​h​ ​u​s​e​r​s
	 */
	shareTitleGeneration: string
	/**
	 * S​h​a​r​i​n​g
	 */
	sharingLabel: string
	/**
	 * S​h​a​r​e​d​ ​m​o​d​e​l​s
	 */
	sharedModels: string
	/**
	 * P​i​c​k​ ​w​h​i​c​h​ ​m​o​d​e​l​s​ ​f​r​o​m​ ​e​a​c​h​ ​s​y​s​t​e​m​ ​s​e​r​v​e​r​ ​a​r​e​ ​a​v​a​i​l​a​b​l​e​ ​t​o​ ​u​s​e​r​s​.​ ​C​o​n​f​i​g​u​r​e​ ​t​h​e​ ​s​e​r​v​e​r​s​ ​t​h​e​m​s​e​l​v​e​s​ ​i​n​ ​t​h​e​ ​S​e​r​v​e​r​s​ ​t​a​b​.
	 */
	sharedModelsDescription: string
	/**
	 * N​o​ ​s​y​s​t​e​m​ ​s​e​r​v​e​r​s​ ​y​e​t​ ​—​ ​a​d​d​ ​o​n​e​ ​i​n​ ​t​h​e​ ​S​e​r​v​e​r​s​ ​t​a​b​.
	 */
	noSystemServers: string
	/**
	 * D​e​f​a​u​l​t​ ​m​o​d​e​l​ ​f​o​r​ ​u​s​e​r​s
	 */
	defaultModelForUsers: string
	/**
	 * —​ ​n​o​n​e​ ​—
	 */
	none: string
	/**
	 * D​e​f​a​u​l​t​ ​—​ ​u​s​e​r​s​ ​m​a​y​ ​c​h​a​n​g​e​ ​i​t
	 */
	defaultUsersMayChange: string
	/**
	 * S​e​l​e​c​t​ ​m​o​d​e​l​s​ ​t​o​ ​s​h​a​r​e
	 */
	selectModelsToShare: string
	/**
	 * {​c​o​u​n​t​}​ ​s​h​a​r​e​d
	 * @param {number} count
	 */
	sharedCount: RequiredParams<'count'>
	/**
	 * N​o​ ​m​o​d​e​l​s​ ​a​v​a​i​l​a​b​l​e​ ​—​ ​c​h​e​c​k​ ​t​h​i​s​ ​s​e​r​v​e​r​ ​i​n​ ​t​h​e​ ​S​e​r​v​e​r​s​ ​t​a​b​.
	 */
	noModelsCheckServersTab: string
	/**
	 * U​s​e​r​s
	 */
	users: string
	/**
	 * A​c​c​o​u​n​t​s​ ​o​n​ ​t​h​i​s​ ​i​n​s​t​a​n​c​e​.
	 */
	usersDescription: string
	/**
	 * C​r​e​a​t​e​ ​a​ ​u​s​e​r
	 */
	createAUser: string
	/**
	 * I​n​i​t​i​a​l​ ​p​a​s​s​w​o​r​d
	 */
	initialPassword: string
	/**
	 * C​r​e​a​t​e​ ​u​s​e​r
	 */
	createUser: string
	/**
	 * A​d​d​ ​u​s​e​r
	 */
	addUser: string
	/**
	 * U​s​e​r​ ​c​r​e​a​t​e​d
	 */
	userCreated: string
	/**
	 * E​m​a​i​l​ ​a​n​d​ ​p​a​s​s​w​o​r​d​ ​a​r​e​ ​r​e​q​u​i​r​e​d
	 */
	emailAndPasswordRequired: string
	/**
	 * D​e​v​e​l​o​p​e​r​ ​o​p​t​i​o​n​s
	 */
	developerOptions: string
	/**
	 * T​o​o​l​s​ ​f​o​r​ ​c​h​e​c​k​i​n​g​ ​f​l​o​w​s​ ​a​ ​u​s​e​r​ ​n​o​r​m​a​l​l​y​ ​o​n​l​y​ ​s​e​e​s​ ​o​n​c​e​.
	 */
	developerOptionsDescription: string
	/**
	 * N​e​w​-​u​s​e​r​ ​o​n​b​o​a​r​d​i​n​g
	 */
	newUserOnboarding: string
	/**
	 * R​e​p​l​a​y​ ​t​h​e​ ​w​e​l​c​o​m​e​ ​t​o​u​r​.​ ​C​l​o​s​e​s​ ​t​h​i​s​ ​d​i​a​l​o​g​;​ ​f​i​n​i​s​h​i​n​g​ ​i​t​ ​m​a​r​k​s​ ​t​h​e​ ​t​o​u​r​ ​a​s​ ​s​e​e​n​ ​a​g​a​i​n​.
	 */
	newUserOnboardingDescription: string
	/**
	 * L​a​u​n​c​h
	 */
	launch: string
	/**
	 * S​e​a​r​c​h​ ​c​o​n​v​e​r​s​a​t​i​o​n​s
	 */
	searchConversations: string
	/**
	 * S​e​a​r​c​h​ ​i​n​ ​e​v​e​r​y​ ​c​o​n​v​e​r​s​a​t​i​o​n​…
	 */
	searchConversationsPlaceholder: string
	/**
	 * S​e​a​r​c​h​ ​"​{​q​u​e​r​y​}​"​ ​i​n​ ​e​v​e​r​y​ ​c​o​n​v​e​r​s​a​t​i​o​n
	 * @param {string} query
	 */
	searchAllConversations: RequiredParams<'query'>
	/**
	 * {​c​o​u​n​t​}​ ​{​{​m​a​t​c​h​|​m​a​t​c​h​e​s​}​}
	 * @param {number} count
	 */
	searchMatches: RequiredParams<'count'>
	/**
	 * N​a​v​i​g​a​t​e
	 */
	searchNavigate: string
	/**
	 * O​p​e​n
	 */
	searchOpen: string
	/**
	 * C​l​o​s​e
	 */
	searchClose: string
	/**
	 * T​y​p​e​ ​t​o​ ​s​e​a​r​c​h​ ​t​h​e​ ​c​o​n​t​e​n​t​ ​o​f​ ​y​o​u​r​ ​c​o​n​v​e​r​s​a​t​i​o​n​s
	 */
	searchStart: string
	/**
	 * K​e​y​b​o​a​r​d​ ​s​h​o​r​t​c​u​t​s
	 */
	keyboardShortcuts: string
	/**
	 * W​h​a​t​ ​t​h​e​ ​a​p​p​ ​a​l​r​e​a​d​y​ ​l​i​s​t​e​n​s​ ​f​o​r​.​ ​C​u​s​t​o​m​i​s​i​n​g​ ​t​h​e​m​ ​w​i​l​l​ ​c​o​m​e​ ​l​a​t​e​r​.
	 */
	keyboardShortcutsDescription: string
	/**
	 * A​n​y​w​h​e​r​e
	 */
	shortcutsGlobal: string
	/**
	 * W​r​i​t​i​n​g​ ​a​ ​m​e​s​s​a​g​e
	 */
	shortcutsComposer: string
	/**
	 * S​e​a​r​c​h​ ​d​i​a​l​o​g
	 */
	shortcutsSearch: string
	/**
	 * D​i​a​l​o​g​s
	 */
	shortcutsDialogs: string
	/**
	 * S​e​n​d
	 */
	shortcutSendMessage: string
	/**
	 * N​e​w​ ​l​i​n​e
	 */
	shortcutNewLine: string
	/**
	 * I​n​ ​t​h​e​ ​e​x​p​a​n​d​e​d​ ​c​o​m​p​o​s​e​r​,​ ​{​m​o​d​}​↵​ ​s​e​n​d​s​ ​a​n​d​ ​↵​ ​i​n​s​e​r​t​s​ ​a​ ​l​i​n​e​ ​—​ ​s​o​ ​a​ ​l​o​n​g​ ​m​e​s​s​a​g​e​ ​c​a​n​ ​b​e​ ​w​r​i​t​t​e​n​ ​w​i​t​h​o​u​t​ ​f​i​r​i​n​g​ ​o​n​ ​e​v​e​r​y​ ​r​e​t​u​r​n​.
	 * @param {string} mod
	 */
	shortcutExpandedNote: RequiredParams<'mod'>
	/**
	 * M​o​v​e​ ​b​e​t​w​e​e​n​ ​t​a​b​s
	 */
	shortcutMoveBetweenTabs: string
	/**
	 * C​l​o​s​e
	 */
	close: string
	/**
	 * C​o​n​v​e​r​s​a​t​i​o​n​ ​l​o​a​d
	 */
	contextLoad: string
	/**
	 * ~​{​t​o​k​e​n​s​}​ ​o​f​ ​{​l​i​m​i​t​}​ ​t​o​k​e​n​s​ ​(​{​p​e​r​c​e​n​t​}​%​)
	 * @param {string} limit
	 * @param {number} percent
	 * @param {string} tokens
	 */
	contextTokensOfLimit: RequiredParams<'limit' | 'percent' | 'tokens'>
	/**
	 * T​h​e​ ​m​o​d​e​l​'​s​ ​c​o​n​t​e​x​t​ ​w​i​n​d​o​w​ ​(​n​u​m​_​c​t​x​)
	 */
	contextLimitFromModel: string
	/**
	 * T​h​r​e​s​h​o​l​d​ ​s​e​t​ ​i​n​ ​S​e​t​t​i​n​g​s​ ​→​ ​C​h​a​t
	 */
	contextLimitFromThreshold: string
	/**
	 * {​c​o​u​n​t​}​ ​{​{​m​e​s​s​a​g​e​|​m​e​s​s​a​g​e​s​}​}​ ​i​n​ ​c​o​n​t​e​x​t
	 * @param {number} count
	 */
	contextMessagesInContext: RequiredParams<'count'>
	/**
	 * {​c​o​u​n​t​}​ ​e​a​r​l​i​e​r​ ​{​{​m​e​s​s​a​g​e​|​m​e​s​s​a​g​e​s​}​}​ ​s​u​m​m​a​r​i​s​e​d
	 * @param {number} count
	 */
	contextMessagesCompacted: RequiredParams<'count'>
	/**
	 * E​s​t​i​m​a​t​e​d​ ​f​r​o​m​ ​t​e​x​t​ ​l​e​n​g​t​h​,​ ​n​o​t​ ​c​o​u​n​t​e​d​ ​b​y​ ​t​h​e​ ​p​r​o​v​i​d​e​r​.
	 */
	contextEstimateNote: string
	/**
	 * {​c​o​u​n​t​}​ ​{​{​m​e​s​s​a​g​e​|​m​e​s​s​a​g​e​s​}​}​ ​s​u​m​m​a​r​i​s​e​d
	 * @param {number} count
	 */
	contextCompacted: RequiredParams<'count'>
	/**
	 * C​o​m​p​a​c​t​e​d​ ​a​u​t​o​m​a​t​i​c​a​l​l​y
	 */
	compactedAutomatically: string
	/**
	 * C​o​m​p​a​c​t​e​d​ ​o​n​ ​r​e​q​u​e​s​t
	 */
	compactedManually: string
	/**
	 * U​n​d​o
	 */
	undoCompaction: string
	/**
	 * R​e​m​o​v​e​ ​t​h​i​s​ ​s​u​m​m​a​r​y​ ​a​n​d​ ​g​i​v​e​ ​t​h​e​ ​m​o​d​e​l​ ​t​h​e​ ​f​u​l​l​ ​h​i​s​t​o​r​y​ ​b​a​c​k
	 */
	undoCompactionHelp: string
	/**
	 * S​u​m​m​a​r​i​s​i​n​g​ ​t​h​e​ ​c​o​n​v​e​r​s​a​t​i​o​n​…
	 */
	compacting: string
	/**
	 * ~​{​t​o​k​e​n​s​}​ ​t​o​k​e​n​s​ ​f​r​e​e​d
	 * @param {string} tokens
	 */
	tokensFreed: RequiredParams<'tokens'>
	/**
	 * {​b​e​f​o​r​e​}​ ​d​o​w​n​ ​t​o​ ​{​a​f​t​e​r​}​.
	 * @param {string} after
	 * @param {string} before
	 */
	tokensFreedDetail: RequiredParams<'after' | 'before'>
	/**
	 * T​h​e​ ​c​o​n​v​e​r​s​a​t​i​o​n​ ​c​o​u​l​d​ ​n​o​t​ ​b​e​ ​c​o​m​p​a​c​t​e​d
	 */
	compactFailed: string
	/**
	 * C​o​m​m​a​n​d​s
	 */
	slashCommands: string
	/**
	 * R​u​n
	 */
	slashRun: string
	/**
	 * S​u​m​m​a​r​i​s​e​ ​t​h​e​ ​c​o​n​v​e​r​s​a​t​i​o​n​ ​s​o​ ​f​a​r​ ​t​o​ ​f​r​e​e​ ​u​p​ ​c​o​n​t​e​x​t
	 */
	compactCommandDescription: string
	/**
	 * T​h​i​s​ ​c​o​n​v​e​r​s​a​t​i​o​n​ ​i​s​ ​t​o​o​ ​s​h​o​r​t​ ​t​o​ ​b​e​ ​w​o​r​t​h​ ​c​o​m​p​a​c​t​i​n​g
	 */
	nothingToCompact: string
	/**
	 * S​l​a​s​h​ ​c​o​m​m​a​n​d​s
	 */
	shortcutsCommands: string
	/**
	 * C​o​m​p​l​e​t​e
	 */
	shortcutCompleteCommand: string
	/**
	 * T​y​p​e​ ​/​ ​a​t​ ​t​h​e​ ​s​t​a​r​t​ ​o​f​ ​a​n​ ​e​m​p​t​y​ ​m​e​s​s​a​g​e​ ​t​o​ ​s​e​e​ ​t​h​e​ ​c​o​m​m​a​n​d​s​.​ ​A​ ​m​e​s​s​a​g​e​ ​t​h​a​t​ ​r​e​a​l​l​y​ ​s​t​a​r​t​s​ ​w​i​t​h​ ​a​ ​s​l​a​s​h​ ​i​s​ ​w​r​i​t​t​e​n​ ​/​/​,​ ​a​n​d​ ​a​n​y​t​h​i​n​g​ ​e​l​s​e​ ​—​ ​a​ ​p​a​t​h​,​ ​a​ ​d​a​t​e​ ​—​ ​i​s​ ​s​e​n​t​ ​a​s​ ​t​y​p​e​d​.
	 */
	shortcutCommandsNote: string
	/**
	 * C​o​m​p​a​c​t​i​o​n
	 */
	compaction: string
	/**
	 * S​u​m​m​a​r​i​s​e​ ​t​h​e​ ​e​a​r​l​i​e​r​ ​p​a​r​t​ ​o​f​ ​a​ ​c​o​n​v​e​r​s​a​t​i​o​n​ ​s​o​ ​i​t​ ​k​e​e​p​s​ ​f​i​t​t​i​n​g​ ​i​n​ ​t​h​e​ ​c​o​n​t​e​x​t​ ​w​i​n​d​o​w​.​ ​N​o​t​h​i​n​g​ ​i​s​ ​d​e​l​e​t​e​d​ ​—​ ​t​h​e​ ​s​u​m​m​a​r​y​ ​r​e​p​l​a​c​e​s​ ​t​h​o​s​e​ ​m​e​s​s​a​g​e​s​ ​o​n​l​y​ ​i​n​ ​w​h​a​t​ ​i​s​ ​s​e​n​t​,​ ​a​n​d​ ​c​a​n​ ​b​e​ ​u​n​d​o​n​e​.
	 */
	compactionDescription: string
	/**
	 * C​o​m​p​a​c​t​i​o​n​ ​m​o​d​e​l
	 */
	compactModel: string
	/**
	 * L​e​a​v​e​ ​e​m​p​t​y​ ​t​o​ ​u​s​e​ ​e​a​c​h​ ​c​o​n​v​e​r​s​a​t​i​o​n​’​s​ ​o​w​n​ ​m​o​d​e​l​.​ ​W​h​a​t​e​v​e​r​ ​t​h​i​s​ ​s​u​m​m​a​r​y​ ​l​e​a​v​e​s​ ​o​u​t​ ​i​s​ ​l​o​s​t​ ​t​o​ ​t​h​e​ ​a​s​s​i​s​t​a​n​t​,​ ​s​o​ ​p​r​e​f​e​r​ ​a​ ​c​a​p​a​b​l​e​ ​m​o​d​e​l​ ​o​v​e​r​ ​a​ ​c​h​e​a​p​ ​o​n​e​.
	 */
	compactModelHelp: string
	/**
	 * C​o​m​p​a​c​t​ ​a​u​t​o​m​a​t​i​c​a​l​l​y
	 */
	autoCompact: string
	/**
	 * S​u​m​m​a​r​i​s​e​ ​o​n​ ​i​t​s​ ​o​w​n​ ​o​n​c​e​ ​a​ ​c​o​n​v​e​r​s​a​t​i​o​n​ ​r​e​a​c​h​e​s​ ​t​h​e​ ​t​h​r​e​s​h​o​l​d​ ​b​e​l​o​w​.
	 */
	autoCompactHelp: string
	/**
	 * T​h​r​e​s​h​o​l​d​ ​(​t​o​k​e​n​s​)
	 */
	compactThreshold: string
	/**
	 * A​l​s​o​ ​t​h​e​ ​c​e​i​l​i​n​g​ ​t​h​e​ ​l​o​a​d​ ​i​n​d​i​c​a​t​o​r​ ​m​e​a​s​u​r​e​s​ ​a​g​a​i​n​s​t​ ​w​h​e​n​ ​t​h​e​ ​p​r​o​v​i​d​e​r​ ​d​o​e​s​ ​n​o​t​ ​a​n​n​o​u​n​c​e​ ​i​t​s​ ​c​o​n​t​e​x​t​ ​w​i​n​d​o​w​ ​—​ ​w​h​i​c​h​ ​i​s​ ​m​o​s​t​ ​o​f​ ​t​h​e​m​.
	 */
	compactThresholdHelp: string
	/**
	 * e​a​c​h​ ​c​o​n​v​e​r​s​a​t​i​o​n​’​s​ ​m​o​d​e​l
	 */
	compactModelOwn: string
	/**
	 * C​o​m​p​a​c​t​i​o​n​ ​s​h​a​r​i​n​g
	 */
	compactionSharing: string
	/**
	 * S​h​a​r​e​ ​y​o​u​r​ ​c​o​m​p​a​c​t​i​o​n​ ​m​o​d​e​l​ ​a​n​d​ ​t​h​r​e​s​h​o​l​d​ ​w​i​t​h​ ​e​v​e​r​y​o​n​e​ ​o​n​ ​t​h​i​s​ ​i​n​s​t​a​n​c​e​.
	 */
	compactionSharingDescription: string
	/**
	 * S​h​a​r​e​ ​c​o​m​p​a​c​t​i​o​n​ ​s​e​t​t​i​n​g​s
	 */
	shareCompaction: string
}

export type TranslationFunctions = {
	/**
	 * Add connection
	 */
	addConnection: () => LocalizedString
	/**
	 * Change your server settings to allow connections from
	 */
	allowConnections: () => LocalizedString
	/**
	 * Allow mixed content
	 */
	allowMixedContent: () => LocalizedString
	/**
	 * API key
	 */
	apiKey: () => LocalizedString
	/**
	 * Key saved
	 */
	apiKeySaved: () => LocalizedString
	/**
	 * Replace
	 */
	apiKeyReplace: () => LocalizedString
	/**
	 * Keep current key
	 */
	apiKeyKeep: () => LocalizedString
	/**
	 * Are you sure you want to delete all knowledge?
	 */
	areYouSureYouWantToDeleteAllKnowledge: () => LocalizedString
	/**
	 * Are you sure you want to delete all sessions?
	 */
	areYouSureYouWantToDeleteAllSessions: () => LocalizedString
	/**
	 * Are you sure you want to delete all preferences?
	 */
	areYouSureYouWantToDeleteAllPreferences: () => LocalizedString
	/**
	 * Are you sure you want to delete all servers?
	 */
	areYouSureYouWantToDeleteAllServers: () => LocalizedString
	/**
	 * Are you sure you want to import? This will overwrite any existing data
	 */
	areYouSureYouWantToImportData: () => LocalizedString
	/**
	 * Are you sure you want to leave?
The completion in progress will stop
	 */
	areYouSureYouWantToLeave: () => LocalizedString
	/**
	 * Assistant
	 */
	assistant: () => LocalizedString
	/**
	 * Attach image
	 */
	attachImage: () => LocalizedString
	/**
	 * Auto
	 */
	automatic: () => LocalizedString
	/**
	 * Automatically check for updates
	 */
	automaticallyCheckForUpdates: () => LocalizedString
	/**
	 * Available models
	 */
	availableModels: () => LocalizedString
	/**
	 * Base URL
	 */
	baseUrl: () => LocalizedString
	/**
	 * Browse the list of available models
	 */
	browseModels: () => LocalizedString
	/**
	 * Cancel
	 */
	cancel: () => LocalizedString
	/**
	 * Can't connect to Ollama server
	 */
	cantConnectToOllamaServer: () => LocalizedString
	/**
	 * Also check no browser extensions are blocking the connection
	 */
	checkBrowserExtensions: () => LocalizedString
	/**
	 * Checking for updates...
	 */
	checkingForUpdates: () => LocalizedString
	/**
	 * Check now
	 */
	checkNow: () => LocalizedString
	/**
	 * Clear
	 */
	clear: () => LocalizedString
	/**
	 * No models available. Sync this connection first.
	 */
	noModelsToRename: () => LocalizedString
	/**
	 * Model names
	 */
	modelNames: () => LocalizedString
	/**
	 * Reset all
	 */
	resetAllNames: () => LocalizedString
	/**
	 * Clear every custom name?
	 */
	confirmResetNames: () => LocalizedString
	/**
	 * Search models
	 */
	searchModels: () => LocalizedString
	/**
	 * Reset
	 */
	reset: () => LocalizedString
	/**
	 * Colour
	 */
	color: () => LocalizedString
	/**
	 * Confirm deletion
	 */
	confirmDeletion: () => LocalizedString
	/**
	 * Confirm edit
	 */
	confirmEdit: () => LocalizedString
	/**
	 * Connection type
	 */
	connectionType: () => LocalizedString
	/**
	 * Connection settings
	 */
	connectionSettings: () => LocalizedString
	/**
	 * Synced
	 */
	synced: () => LocalizedString
	/**
	 * Not synced
	 */
	notSynced: () => LocalizedString
	/**
	 * Last synced {date}
	 */
	lastSynced: (arg: { date: string }) => LocalizedString
	/**
	 * Never synced — run a sync to load its models
	 */
	neverSynced: () => LocalizedString
	/**
	 * {count} model{{s}}
	 */
	modelsCount: (arg: { count: number }) => LocalizedString
	/**
	 * Connecting...
	 */
	connecting: () => LocalizedString
	/**
	 * Connection has been verified and is ready to use
	 */
	connectionIsVerified: () => LocalizedString
	/**
	 * Connection failed to verify, check the connection settings and try again
	 */
	connectionFailedToVerify: () => LocalizedString
	/**
	 * Content
	 */
	content: () => LocalizedString
	/**
	 * Controls
	 */
	controls: () => LocalizedString
	/**
	 * Advanced controls are currently only available for Ollama models
	 */
	controlsOnlyAvailableForOllama: () => LocalizedString
	/**
	 * Copy
	 */
	copy: () => LocalizedString
	/**
	 * Server unreachable
	 */
	couldntReachServer: () => LocalizedString
	/**
	 * GitHub unreachable
	 */
	couldntReachReleases: () => LocalizedString
	/**
	 * Never checked
	 */
	neverChecked: () => LocalizedString
	/**
	 * Up to date
	 */
	upToDate: () => LocalizedString
	/**
	 * just now
	 */
	justNow: () => LocalizedString
	/**
	 * {version} available
	 */
	versionAvailable: (arg: { version: string }) => LocalizedString
	/**
	 * Checked {when}
	 */
	lastChecked: (arg: { when: string }) => LocalizedString
	/**
	 * Release notes
	 */
	releaseNotes: () => LocalizedString
	/**
	 * Couldn't connect to Ollama server
	 */
	couldntConnectToOllamaServer: () => LocalizedString
	/**
	 * Creating a tunnel
	 */
	creatingTunnel: () => LocalizedString
	/**
	 * Current version
	 */
	currentVersion: () => LocalizedString
	/**
	 * Danger zone
	 */
	dangerZone: () => LocalizedString
	/**
	 * Dark
	 */
	dark: () => LocalizedString
	/**
	 * Delete
	 */
	'delete': () => LocalizedString
	/**
	 * Remove
	 */
	remove: () => LocalizedString
	/**
	 * Back
	 */
	back: () => LocalizedString
	/**
	 * Add context
	 */
	addContext: () => LocalizedString
	/**
	 * Attach document
	 */
	attachDocument: () => LocalizedString
	/**
	 * Sidebar
	 */
	sidebar: () => LocalizedString
	/**
	 * Show pin and delete on each row
	 */
	showListQuickActions: () => LocalizedString
	/**
	 * Off, both stay in the right-click menu, where they cannot cover a title or be clicked by mistake. The menu also keeps a conversation as knowledge.
	 */
	showListQuickActionsHelp: () => LocalizedString
	/**
	 * Keep in the Library
	 */
	keepInLibrary: () => LocalizedString
	/**
	 * Save as knowledge
	 */
	saveAsKnowledge: () => LocalizedString
	/**
	 * Copy as Markdown
	 */
	copyAsMarkdown: () => LocalizedString
	/**
	 * Copy as JSON
	 */
	copyAsJson: () => LocalizedString
	/**
	 * Notes, references, anything worth handing to a model again
	 */
	knowledgeModalHint: () => LocalizedString
	/**
	 * Name this knowledge
	 */
	knowledgeNamePlaceholder: () => LocalizedString
	/**
	 * Paste or write what the model should know
	 */
	knowledgeContentPlaceholder: () => LocalizedString
	/**
	 * ~{tokens} tokens
	 */
	knowledgeTokens: (arg: { tokens: string }) => LocalizedString
	/**
	 * Text
	 */
	editorPlain: () => LocalizedString
	/**
	 * Code
	 */
	editorCode: () => LocalizedString
	/**
	 * Rename
	 */
	rename: () => LocalizedString
	/**
	 * No collection
	 */
	noCollection: () => LocalizedString
	/**
	 * Find or create a collection
	 */
	collectionSearchPlaceholder: () => LocalizedString
	/**
	 * Create "{name}"
	 */
	createCollectionNamed: (arg: { name: string }) => LocalizedString
	/**
	 * {count} {{item|items}}
	 */
	knowledgeCount: (arg: { count: number }) => LocalizedString
	/**
	 * Delete the collection {name}? Its knowledge is kept.
	 */
	deleteCollectionConfirm: (arg: { name: string }) => LocalizedString
	/**
	 * {count} {{page|pages}}
	 */
	pageCount: (arg: { count: number }) => LocalizedString
	/**
	 * {name} could not be read
	 */
	documentFailed: (arg: { name: string }) => LocalizedString
	/**
	 * No text could be read from {name}
	 */
	documentEmpty: (arg: { name: string }) => LocalizedString
	/**
	 * This PDF looks scanned
	 */
	documentLooksScanned: () => LocalizedString
	/**
	 * Most of this PDF is images
	 */
	documentMostlyImages: () => LocalizedString
	/**
	 * Send the pages as images
	 */
	documentPagesAsImages: () => LocalizedString
	/**
	 * There is no text to extract, only pictures of it. A vision model can read the pages directly, up to {max} of them. Turn on OCR in Settings to read them as text instead.
	 */
	documentPagesAsImagesHelp: (arg: { max: number }) => LocalizedString
	/**
	 * Documents
	 */
	documentsTitle: () => LocalizedString
	/**
	 * Attach a PDF, a Word file or a spreadsheet and its text goes into the conversation. Files are read in your browser and never uploaded.
	 */
	documentsDescription: () => LocalizedString
	/**
	 * Read attached documents
	 */
	documentsToggle: () => LocalizedString
	/**
	 * Supports PDF, DOCX, PPTX, XLSX, ODT, ODP, ODS, RTF, EPUB, CSV, HTML, Markdown and plain text. Turned off, the reader is never downloaded and documents cannot be attached.
	 */
	documentsHelp: () => LocalizedString
	/**
	 * Read text inside images (OCR)
	 */
	documentOcrToggle: () => LocalizedString
	/**
	 * For scans and pictures of text. It is slow, a few seconds per page, and the result is approximate: expect tables and columns to come out flattened. On first use it downloads an OCR engine and its language data, from a public CDN unless this instance hosts them itself.
	 */
	documentOcrHelp: () => LocalizedString
	/**
	 * OCR language
	 */
	documentOcrLanguage: () => LocalizedString
	/**
	 * Tesseract language codes, for example eng, fra, deu. Combine them with a plus sign: eng+fra. Each language is a separate download.
	 */
	documentOcrLanguageHelp: () => LocalizedString
	/**
	 * Delete knowledge
	 */
	deleteKnowledge: () => LocalizedString
	/**
	 * Delete server
	 */
	deleteServer: () => LocalizedString
	/**
	 * Delete session
	 */
	deleteSession: () => LocalizedString
	/**
	 * Disconnected
	 */
	disconnected: () => LocalizedString
	/**
	 * Dismiss
	 */
	dismiss: () => LocalizedString
	/**
	 * Download model
	 */
	downloadModel: () => LocalizedString
	/**
	 * Edit
	 */
	edit: () => LocalizedString
	/**
	 * Edit title
	 */
	editTitle: () => LocalizedString
	/**
	 * No knowledge
	 */
	emptyKnowledge: () => LocalizedString
	/**
	 * No sessions
	 */
	emptySessions: () => LocalizedString
	/**
	 * Error
	 */
	error: () => LocalizedString
	/**
	 * Export
	 */
	'export': () => LocalizedString
	/**
	 * F16 KV
	 */
	f16Kv: () => LocalizedString
	/**
	 * Frequency penalty
	 */
	frequencyPenalty: () => LocalizedString
	/**
	 * Sorry, something went wrong
	 */
	genericError: () => LocalizedString
	/**
	 * Go to downloads
	 */
	goToDownloads: () => LocalizedString
	/**
	 * Go to knowledge
	 */
	goToKnowledge: () => LocalizedString
	/**
	 * Go to releases
	 */
	goToReleases: () => LocalizedString
	/**
	 * How to obtain an API key from OpenAI?
	 */
	howToObtainOpenAIKey: () => LocalizedString
	/**
	 * How to update Docker container?
	 */
	howToUpdateDocker: () => LocalizedString
	/**
	 * Import
	 */
	'import': () => LocalizedString
	/**
	 * Interface
	 */
	'interface': () => LocalizedString
	/**
	 * There was an internal server error, please try again later
	 */
	internalServerError: () => LocalizedString
	/**
	 * You are on the latest version
	 */
	isCurrentVersionLatest: () => LocalizedString
	/**
	 * A newer version is available
	 */
	isLatestVersion: () => LocalizedString
	/**
	 * Knowledge
	 */
	knowledge: () => LocalizedString
	/**
	 * Knowledge saved
	 */
	knowledgeSaved: () => LocalizedString
	/**
	 * Label
	 */
	label: () => LocalizedString
	/**
	 * Language
	 */
	language: () => LocalizedString
	/**
	 * Recently used models
	 */
	lastUsedModels: () => LocalizedString
	/**
	 * Light
	 */
	light: () => LocalizedString
	/**
	 * Low VRAM
	 */
	lowVram: () => LocalizedString
	/**
	 * Main GPU
	 */
	mainGpu: () => LocalizedString
	/**
	 * Messages
	 */
	messages: () => LocalizedString
	/**
	 * Min P
	 */
	minP: () => LocalizedString
	/**
	 * Mirostat
	 */
	mirostat: () => LocalizedString
	/**
	 * Mirostat ETA
	 */
	mirostatEta: () => LocalizedString
	/**
	 * Mirostat Tau
	 */
	mirostatTau: () => LocalizedString
	/**
	 * Model not found
	 */
	modelNotFound: () => LocalizedString
	/**
	 * Model options
	 */
	modelOptions: () => LocalizedString
	/**
	 * {model} was downloaded
	 */
	modelWasDownloaded: (arg: { model: string }) => LocalizedString
	/**
	 * Model names filter
	 */
	modelsFilter: () => LocalizedString
	/**
	 * Name
	 */
	name: () => LocalizedString
	/**
	 * New knowledge
	 */
	newKnowledge: () => LocalizedString
	/**
	 * New session
	 */
	newSession: () => LocalizedString
	/**
	 * No API key
	 */
	noApiKey: () => LocalizedString
	/**
	 * Create new knowledge or choose one from the list
	 */
	noKnowledgeChosen: () => LocalizedString
	/**
	 * No recently used models
	 */
	noRecentModels: () => LocalizedString
	/**
	 * No server connections, add one to start
	 */
	noServerConnections: () => LocalizedString
	/**
	 * Create a new session or choose an existing one from the list
	 */
	noSessionChosen: () => LocalizedString
	/**
	 * The page you are looking for does not exist
	 */
	notFound: () => LocalizedString
	/**
	 * Num batch
	 */
	numBatch: () => LocalizedString
	/**
	 * Context size
	 */
	numCtx: () => LocalizedString
	/**
	 * Num GPU
	 */
	numGpu: () => LocalizedString
	/**
	 * Num keep
	 */
	numKeep: () => LocalizedString
	/**
	 * Num predict
	 */
	numPredict: () => LocalizedString
	/**
	 * Number of threads
	 */
	numThread: () => LocalizedString
	/**
	 * NUMA
	 */
	numa: () => LocalizedString
	/**
	 * Ollama
	 */
	ollama: () => LocalizedString
	/**
	 * Ollama's library
	 */
	ollamaLibrary: () => LocalizedString
	/**
	 * OpenAI: Official API
	 */
	openAIOfficialAPI: () => LocalizedString
	/**
	 * OpenAI: Compatible servers (i.e. llama.cpp)
	 */
	openAICompatible: () => LocalizedString
	/**
	 * Other models
	 */
	otherModels: () => LocalizedString
	/**
	 * Penalize newline
	 */
	penalizeNewline: () => LocalizedString
	/**
	 * Preferences
	 */
	preferences: () => LocalizedString
	/**
	 * Presence penalty
	 */
	presencePenalty: () => LocalizedString
	/**
	 * Prompt
	 */
	prompt: () => LocalizedString
	/**
	 * Write literally anything
	 */
	promptPlaceholder: () => LocalizedString
	/**
	 * Pull model
	 */
	pullModel: () => LocalizedString
	/**
	 * Model tag (e.g. llama3.1)
	 */
	pullModelPlaceholder: () => LocalizedString
	/**
	 * Pulling model
	 */
	pullingModel: () => LocalizedString
	/**
	 * Random
	 */
	random: () => LocalizedString
	/**
	 * Reasoning
	 */
	reasoning: () => LocalizedString
	/**
	 * Read {count} page{{s}}
	 */
	pagesRead: (arg: { count: number }) => LocalizedString
	/**
	 * Could not read the pages
	 */
	pagesReadFailed: () => LocalizedString
	/**
	 * Searching the web
	 */
	searchingTheWeb: () => LocalizedString
	/**
	 * Reading the pages
	 */
	readingPages: () => LocalizedString
	/**
	 * Thinking
	 */
	thinkingActivity: () => LocalizedString
	/**
	 * {count} result{{s}}
	 */
	searchResults: (arg: { count: number }) => LocalizedString
	/**
	 * No results
	 */
	noWebResults: () => LocalizedString
	/**
	 * Searched the web
	 */
	searchedTheWeb: () => LocalizedString
	/**
	 * Done
	 */
	activityDone: () => LocalizedString
	/**
	 * Show more
	 */
	showMore: () => LocalizedString
	/**
	 * Show less
	 */
	showLess: () => LocalizedString
	/**
	 * Refresh to update
	 */
	refreshToUpdate: () => LocalizedString
	/**
	 * Release history
	 */
	releaseHistory: () => LocalizedString
	/**
	 * Repeat last N
	 */
	repeatLastN: () => LocalizedString
	/**
	 * Repeat penalty
	 */
	repeatPenalty: () => LocalizedString
	/**
	 * Retry
	 */
	retry: () => LocalizedString
	/**
	 * Run
	 */
	run: () => LocalizedString
	/**
	 * Runtime options
	 */
	runtimeOptions: () => LocalizedString
	/**
	 * Save
	 */
	save: () => LocalizedString
	/**
	 * Search
	 */
	search: () => LocalizedString
	/**
	 * No results found
	 */
	searchEmpty: () => LocalizedString
	/**
	 * Seed
	 */
	seed: () => LocalizedString
	/**
	 * See docs
	 */
	seeDocs: () => LocalizedString
	/**
	 * Servers
	 */
	servers: () => LocalizedString
	/**
	 * Server configuration was updated and needs to be re-verified in "Settings"
	 */
	serverSettingsUpdated: () => LocalizedString
	/**
	 * Session
	 */
	session: () => LocalizedString
	/**
	 * Sessions
	 */
	sessions: () => LocalizedString
	/**
	 * Settings
	 */
	settings: () => LocalizedString
	/**
	 * Sorry, something went wrong
	 */
	somethingWentWrong: () => LocalizedString
	/**
	 * Stop sequence
	 */
	stop: () => LocalizedString
	/**
	 * Scroll to the latest message
	 */
	scrollToBottom: () => LocalizedString
	/**
	 * Stop completion
	 */
	stopCompletion: () => LocalizedString
	/**
	 * Stop response
	 */
	stopResponse: () => LocalizedString
	/**
	 * Success
	 */
	success: () => LocalizedString
	/**
	 * System
	 */
	system: () => LocalizedString
	/**
	 * System prompt
	 */
	systemPrompt: () => LocalizedString
	/**
	 * Temperature
	 */
	temperature: () => LocalizedString
	/**
	 * TFS Z
	 */
	tfsZ: () => LocalizedString
	/**
	 * Top K
	 */
	topK: () => LocalizedString
	/**
	 * Top P
	 */
	topP: () => LocalizedString
	/**
	 * If you want to connect to an Ollama server that is not available on {hostname} or {ip} try
	 */
	tryingToConnectNotLocalhost: (arg: { hostname: string, ip: string }) => LocalizedString
	/**
	 * Typical P
	 */
	typicalP: () => LocalizedString
	/**
	 * You have unsaved changes that will be lost. Continue?
	 */
	unsavedChangesWillBeLost: () => LocalizedString
	/**
	 * Use MLOCK
	 */
	useMlock: () => LocalizedString
	/**
	 * Use MMAP
	 */
	useMmap: () => LocalizedString
	/**
	 * Use models from this server
	 */
	useModelsFromThisServer: () => LocalizedString
	/**
	 * Sync
	 */
	sync: () => LocalizedString
	/**
	 * Verify
	 */
	verify: () => LocalizedString
	/**
	 * Web fetch
	 */
	webFetchSharing: () => LocalizedString
	/**
	 * Let users read the pages their messages link to, with your own limits. Sharing it while it is off in your Tools tab disables it for everyone.
	 */
	webFetchSharingDescription: () => LocalizedString
	/**
	 * Share web fetch with users
	 */
	shareWebFetch: () => LocalizedString
	/**
	 * Currently sharing: {pages} pages, {chars}k characters per page.
	 */
	currentlySharingWebFetch: (arg: { chars: unknown, pages: unknown }) => LocalizedString
	/**
	 * Currently sharing: off — no user may read pages.
	 */
	currentlySharingWebFetchOff: () => LocalizedString
	/**
	 * Web fetch
	 */
	webFetchTitle: () => LocalizedString
	/**
	 * Read the pages a message links to, instead of searching around them.
	 */
	webFetchDescription: () => LocalizedString
	/**
	 * Read linked pages
	 */
	webFetchToggle: () => LocalizedString
	/**
	 * On by default in new conversations
	 */
	webFetchByDefault: () => LocalizedString
	/**
	 * Pages read per message
	 */
	webFetchMaxPages: () => LocalizedString
	/**
	 * Characters kept per page
	 */
	webFetchMaxChars: () => LocalizedString
	/**
	 * Only explicit http(s) links are read. Requests are made by the server, which refuses private and local addresses.
	 */
	webFetchHint: () => LocalizedString
	/**
	 * Enabled by your administrator — up to {pages} pages per message.
	 */
	webFetchLockedOn: (arg: { pages: unknown }) => LocalizedString
	/**
	 * Disabled by your administrator.
	 */
	webFetchLockedOff: () => LocalizedString
	/**
	 * Version
	 */
	version: () => LocalizedString
	/**
	 * View release
	 */
	viewRelease: () => LocalizedString
	/**
	 * Vocab only
	 */
	vocabOnly: () => LocalizedString
	/**
	 * Write a prompt to start a new session
	 */
	writePromptToStart: () => LocalizedString
	/**
	 * You
	 */
	you: () => LocalizedString
	/**
	 * Content copied, but your connection is not private
	 */
	copiedNotPrivate: () => LocalizedString
	/**
	 * Couldn't copy content. Connection is not private
	 */
	notCopiedNotPrivate: () => LocalizedString
	/**
	 * Import successful
	 */
	importSuccess: () => LocalizedString
	/**
	 * Import failed
	 */
	importError: () => LocalizedString
	/**
	 * Deleted successfully
	 */
	deleteSuccess: () => LocalizedString
	/**
	 * Connections, model filters and labels
	 */
	serversDescription: () => LocalizedString
	/**
	 * Language, theme, recently used models, etc
	 */
	preferencesDescription: () => LocalizedString
	/**
	 * Entire session history, attachments and custom model settings
	 */
	sessionsDescription: () => LocalizedString
	/**
	 * Entire knowledge base
	 */
	knowledgeDescription: () => LocalizedString
	/**
	 * Expand sidebar
	 */
	expandSidebar: () => LocalizedString
	/**
	 * Collapse sidebar
	 */
	collapseSidebar: () => LocalizedString
	/**
	 * Expand the prompt
	 */
	expandPrompt: () => LocalizedString
	/**
	 * Collapse the prompt
	 */
	collapsePrompt: () => LocalizedString
	/**
	 * Profile
	 */
	profile: () => LocalizedString
	/**
	 * Good morning
	 */
	goodMorning: () => LocalizedString
	/**
	 * Good afternoon
	 */
	goodAfternoon: () => LocalizedString
	/**
	 * Good evening
	 */
	goodEvening: () => LocalizedString
	/**
	 * How can I help you today?
	 */
	howCanIHelp: () => LocalizedString
	/**
	 * Recent sessions
	 */
	recentSessions: () => LocalizedString
	/**
	 * Product ID
	 */
	productId: () => LocalizedString
	/**
	 * How to obtain an API key?
	 */
	howToObtainApiKey: () => LocalizedString
	/**
	 * Advanced
	 */
	advancedSettings: () => LocalizedString
	/**
	 * Default model
	 */
	defaultModel: () => LocalizedString
	/**
	 * Title model
	 */
	titleModel: () => LocalizedString
	/**
	 * Generate titles with AI
	 */
	generateTitlesWithAI: () => LocalizedString
	/**
	 * Automatically name new sessions after the first reply, using the selected model
	 */
	generateTitlesWithAIHelp: () => LocalizedString
	/**
	 * Theme
	 */
	theme: () => LocalizedString
	/**
	 * Translucent surfaces
	 */
	surfaceTransparency: () => LocalizedString
	/**
	 * Amount of transparency
	 */
	surfaceTransparencyStrength: () => LocalizedString
	/**
	 * Theme style
	 */
	themeStyle: () => LocalizedString
	/**
	 * First name
	 */
	firstName: () => LocalizedString
	/**
	 * Last name
	 */
	lastName: () => LocalizedString
	/**
	 * Role
	 */
	role: () => LocalizedString
	/**
	 * Avatar URL
	 */
	avatarUrl: () => LocalizedString
	/**
	 * Avatar color
	 */
	avatarColor: () => LocalizedString
	/**
	 * Reset everything
	 */
	resetEverything: () => LocalizedString
	/**
	 * Permanently delete all data and reset the app
	 */
	resetEverythingDescription: () => LocalizedString
	/**
	 * This will permanently delete ALL your data — sessions, knowledge, servers and preferences. This cannot be undone. Make sure you have a backup. Continue?
	 */
	resetEverythingConfirm: () => LocalizedString
	/**
	 * New chat
	 */
	newChat: () => LocalizedString
	/**
	 * Chats
	 */
	chats: () => LocalizedString
	/**
	 * Library
	 */
	library: () => LocalizedString
	/**
	 * Search chats & personas
	 */
	searchChatsPersonas: () => LocalizedString
	/**
	 * No matches
	 */
	noMatches: () => LocalizedString
	/**
	 * Personas
	 */
	personas: () => LocalizedString
	/**
	 * Pinned
	 */
	groupPinned: () => LocalizedString
	/**
	 * Today
	 */
	groupToday: () => LocalizedString
	/**
	 * Yesterday
	 */
	groupYesterday: () => LocalizedString
	/**
	 * Previous 7 days
	 */
	groupPrevious7Days: () => LocalizedString
	/**
	 * Previous 30 days
	 */
	groupPrevious30Days: () => LocalizedString
	/**
	 * Older
	 */
	groupOlder: () => LocalizedString
	/**
	 * Pin
	 */
	pin: () => LocalizedString
	/**
	 * Unpin
	 */
	unpin: () => LocalizedString
	/**
	 * Connected
	 */
	connected: () => LocalizedString
	/**
	 * No server connected
	 */
	noServerConnected: () => LocalizedString
	/**
	 * Untitled
	 */
	untitled: () => LocalizedString
	/**
	 * All conversations
	 */
	allConversations: () => LocalizedString
	/**
	 * Administrator
	 */
	administrator: () => LocalizedString
	/**
	 * User
	 */
	user: () => LocalizedString
	/**
	 * Everything you create lives here — your personas and your knowledge.
	 */
	librarySubtitle: () => LocalizedString
	/**
	 * Shared with users
	 */
	sharedWithUsers: () => LocalizedString
	/**
	 * Shared
	 */
	shared: () => LocalizedString
	/**
	 * New persona
	 */
	newPersona: () => LocalizedString
	/**
	 * Shared by admin
	 */
	sharedByAdmin: () => LocalizedString
	/**
	 * Install
	 */
	install: () => LocalizedString
	/**
	 * Import persona
	 */
	importPersona: () => LocalizedString
	/**
	 * Import knowledge
	 */
	importKnowledge: () => LocalizedString
	/**
	 * New collection
	 */
	newCollection: () => LocalizedString
	/**
	 * Edit persona
	 */
	editPersona: () => LocalizedString
	/**
	 * Invalid file
	 */
	invalidFile: () => LocalizedString
	/**
	 * No personas found in this file
	 */
	noPersonasInFile: () => LocalizedString
	/**
	 * No knowledge found in this file
	 */
	noKnowledgeInFile: () => LocalizedString
	/**
	 * Installed “{name}”
	 */
	installedPersona: (arg: { name: string }) => LocalizedString
	/**
	 * Imported {count} persona{{s}}
	 */
	importedPersonas: (arg: { count: number }) => LocalizedString
	/**
	 * Imported {count} knowledge item{{s}}
	 */
	importedCollections: (arg: { count: number }) => LocalizedString
	/**
	 * Send
	 */
	send: () => LocalizedString
	/**
	 * Other…
	 */
	otherChoice: () => LocalizedString
	/**
	 * Type your answer
	 */
	otherChoicePlaceholder: () => LocalizedString
	/**
	 * Choose one or more
	 */
	multipleAllowed: () => LocalizedString
	/**
	 * Preparing options
	 */
	preparingOptions: () => LocalizedString
	/**
	 * Follow the model while it works
	 */
	autoExpandReasoningBlocks: () => LocalizedString
	/**
	 * Unfolds the steps as they happen and folds them away when the answer starts. Off, they stay folded under a single line.
	 */
	autoExpandReasoningBlocksHelp: () => LocalizedString
	/**
	 * Defaults
	 */
	defaults: () => LocalizedString
	/**
	 * set by admin
	 */
	setByAdmin: () => LocalizedString
	/**
	 * shared by admin
	 */
	sharedByAdminBadge: () => LocalizedString
	/**
	 * server default
	 */
	serverDefaultBadge: () => LocalizedString
	/**
	 * Restore server default
	 */
	restoreServerDefault: () => LocalizedString
	/**
	 * System prompts
	 */
	systemPromptsTitle: () => LocalizedString
	/**
	 * Applied to every new chat (lowest priority). A per-model prompt or a per-chat prompt overrides it.
	 */
	systemPromptsDescription: () => LocalizedString
	/**
	 * Global prompt
	 */
	globalPrompt: () => LocalizedString
	/**
	 * e.g. You are concise and answer in the user's language…
	 */
	globalPromptPlaceholder: () => LocalizedString
	/**
	 * Per-model prompts
	 */
	perModelPrompts: () => LocalizedString
	/**
	 * + Add a model
	 */
	addAModel: () => LocalizedString
	/**
	 * Remove the prompt for {model}
	 */
	removeModelPrompt: (arg: { model: string }) => LocalizedString
	/**
	 * Prompt for {model}…
	 */
	promptForModel: (arg: { model: string }) => LocalizedString
	/**
	 * Extends the global prompt
	 */
	extendsGlobalPrompt: () => LocalizedString
	/**
	 * Replaces the global prompt
	 */
	replacesGlobalPrompt: () => LocalizedString
	/**
	 * extends global
	 */
	extendsGlobalShort: () => LocalizedString
	/**
	 * replaces global
	 */
	replacesGlobalShort: () => LocalizedString
	/**
	 * No per-model prompts yet. Add one to tailor instructions for a specific model.
	 */
	noPerModelPrompts: () => LocalizedString
	/**
	 * On
	 */
	on: () => LocalizedString
	/**
	 * Off
	 */
	off: () => LocalizedString
	/**
	 * Web search
	 */
	webSearch: () => LocalizedString
	/**
	 * Backend URL (degoog / SearXNG)
	 */
	webSearchBackendUrl: () => LocalizedString
	/**
	 * Backend
	 */
	webSearchBackend: () => LocalizedString
	/**
	 * API token (optional, for protected instances)
	 */
	webSearchToken: () => LocalizedString
	/**
	 * •••••••• (set)
	 */
	webSearchTokenSet: () => LocalizedString
	/**
	 * Enable web search by default
	 */
	webSearchByDefault: () => LocalizedString
	/**
	 * Let the model decide when to search the web automatically
	 */
	webSearchAuto: () => LocalizedString
	/**
	 * The model first decides whether a question needs the web. Most modern models (even Ollama) handle this well, but a few small ones may not.
	 */
	webSearchAutoHelp: () => LocalizedString
	/**
	 * Web search isn't available yet. An admin can configure it for this instance.
	 */
	webSearchUnavailable: () => LocalizedString
	/**
	 * Native tool calling
	 */
	nativeToolsTitle: () => LocalizedString
	/**
	 * How the model is given the web tools: as text instructions it answers in its replies, or as tool calls the provider transports for it.
	 */
	nativeToolsDescription: () => LocalizedString
	/**
	 * Mode
	 */
	nativeToolsLabel: () => LocalizedString
	/**
	 * Text instructions (works everywhere)
	 */
	nativeToolsOff: () => LocalizedString
	/**
	 * Native where supported
	 */
	nativeToolsAuto: () => LocalizedString
	/**
	 * Always native
	 */
	nativeToolsForce: () => LocalizedString
	/**
	 * Native calling lets the model search on its own, so no extra request is needed to decide for it. Ollama reports per model whether it can; the hosted providers all can. Choose "always" only for a self-hosted endpoint you know supports it, since a model offered tools it cannot call will improvise instead of failing.
	 */
	nativeToolsHelp: () => LocalizedString
	/**
	 * Interactive choices
	 */
	interactiveChoicesTitle: () => LocalizedString
	/**
	 * When a request is ambiguous and depends on a preference, the model can present a few tappable options instead of guessing. Your selection is sent as a normal message.
	 */
	interactiveChoicesDescription: () => LocalizedString
	/**
	 * Let the model offer quick-choice buttons
	 */
	interactiveChoicesToggle: () => LocalizedString
	/**
	 * Current date
	 */
	currentDateTitle: () => LocalizedString
	/**
	 * A model has no clock and otherwise assumes its training-cutoff date — rejecting newer facts as impossible. This prepends the current date/time (your local timezone) to each request so it stays anchored in the present.
	 */
	currentDateDescription: () => LocalizedString
	/**
	 * Tell the model today's date and time
	 */
	currentDateToggle: () => LocalizedString
	/**
	 * System instructions
	 */
	systemInstructionsTitle: () => LocalizedString
	/**
	 * The behind-the-scenes prompts {app} injects for the features above. Pick one to view or tweak it — leave it on the default unless you know what you are changing.
	 */
	systemInstructionsDescription: (arg: { app: string }) => LocalizedString
	/**
	 * Placeholders
	 */
	placeholders: () => LocalizedString
	/**
	 * Reset to default
	 */
	resetToDefault: () => LocalizedString
	/**
	 * Backup & restore
	 */
	backupAndRestore: () => LocalizedString
	/**
	 * Export or import everything (sessions, knowledge, servers, preferences) in a single file.
	 */
	backupAndRestoreDescription: () => LocalizedString
	/**
	 * Backup
	 */
	backup: () => LocalizedString
	/**
	 * Restore
	 */
	restore: () => LocalizedString
	/**
	 * By category
	 */
	byCategory: () => LocalizedString
	/**
	 * Export, import or delete each kind of data on its own.
	 */
	byCategoryDescription: () => LocalizedString
	/**
	 * Your saved characters and their settings
	 */
	personasDescription: () => LocalizedString
	/**
	 * Are you sure you want to delete all personas?
	 */
	areYouSureYouWantToDeleteAllPersonas: () => LocalizedString
	/**
	 * Are you sure? This cannot be undone.
	 */
	confirmResetEverything: () => LocalizedString
	/**
	 * Yes, delete everything
	 */
	yesDeleteEverything: () => LocalizedString
	/**
	 * System servers
	 */
	systemServers: () => LocalizedString
	/**
	 * Your servers
	 */
	yourServers: () => LocalizedString
	/**
	 * Providers are managed by your administrator.
	 */
	providersManagedByAdmin: () => LocalizedString
	/**
	 * Add a server
	 */
	addAServer: () => LocalizedString
	/**
	 * Optional
	 */
	optional: () => LocalizedString
	/**
	 * Verifying…
	 */
	verifying: () => LocalizedString
	/**
	 * {count} model{{s}} found
	 */
	modelsFound: (arg: { count: number }) => LocalizedString
	/**
	 * Server added
	 */
	serverAdded: () => LocalizedString
	/**
	 * Request failed
	 */
	requestFailed: () => LocalizedString
	/**
	 * Base URL is required
	 */
	baseUrlRequired: () => LocalizedString
	/**
	 * Connection failed
	 */
	connectionFailed: () => LocalizedString
	/**
	 * Connection verified — {count} model{{s}}
	 */
	connectionVerifiedWithModels: (arg: { count: number }) => LocalizedString
	/**
	 * Appearance
	 */
	appearance: () => LocalizedString
	/**
	 * Home screen
	 */
	homeScreen: () => LocalizedString
	/**
	 * Show greeting header
	 */
	showGreetingHeader: () => LocalizedString
	/**
	 * Show prompt suggestions
	 */
	showPromptSuggestions: () => LocalizedString
	/**
	 * Show recent personas
	 */
	showRecentPersonas: () => LocalizedString
	/**
	 * Show recent sessions
	 */
	showRecentSessions: () => LocalizedString
	/**
	 * How many to show
	 */
	howManyToShow: () => LocalizedString
	/**
	 * Tint my messages with the accent colour
	 */
	accentUserMessages: () => LocalizedString
	/**
	 * Show the time on each message
	 */
	showMessageTimestamps: () => LocalizedString
	/**
	 * Fade messages a summary has replaced
	 */
	fadeCompactedMessages: () => LocalizedString
	/**
	 * Compacted messages stay on screen but are no longer sent to the model. Fading them shows where the live context begins; hover one to read it at full strength.
	 */
	fadeCompactedMessagesHelp: () => LocalizedString
	/**
	 * Pin personas you talk to at the top of the sidebar
	 */
	pinPersonasInSidebar: () => LocalizedString
	/**
	 * Background
	 */
	background: () => LocalizedString
	/**
	 * Background image
	 */
	backgroundImage: () => LocalizedString
	/**
	 * Shown behind the app. The sidebar is translucent so the picture reads through it, the conversation stays opaque so nothing has to be read off a photograph. The ones shipped with the app cost nothing to store; your own is kept with your settings, which travel.
	 */
	backgroundImageHelp: () => LocalizedString
	/**
	 * Choose an image
	 */
	chooseImage: () => LocalizedString
	/**
	 * Replace
	 */
	replaceImage: () => LocalizedString
	/**
	 * None
	 */
	noBackground: () => LocalizedString
	/**
	 * Background blur
	 */
	backgroundBlur: () => LocalizedString
	/**
	 * Use your own image
	 */
	useYourOwnImage: () => LocalizedString
	/**
	 * Your image
	 */
	yourImage: () => LocalizedString
	/**
	 * max. 3 MB
	 */
	maxImageSize: () => LocalizedString
	/**
	 * That picture is over 3 MB. Choose a lighter one, or resize it first.
	 */
	imageTooLarge: () => LocalizedString
	/**
	 * Floating conversation bar
	 */
	floatingChatHeader: () => LocalizedString
	/**
	 * A pill hovering over the conversation, matching the composer at the other end, with the text passing around both. Off, it goes back to being the top edge of the column, where a background image reaches it.
	 */
	floatingChatHeaderHelp: () => LocalizedString
	/**
	 * Use the compact header
	 */
	compactSidebarHeader: () => LocalizedString
	/**
	 * New chat moves onto the search row, and the personas become a row of avatars. More room for the list, fewer labels.
	 */
	compactSidebarHeaderHelp: () => LocalizedString
	/**
	 * Source
	 */
	source: () => LocalizedString
	/**
	 * Documentation
	 */
	documentation: () => LocalizedString
	/**
	 * Buy me a coffee
	 */
	buyMeACoffee: () => LocalizedString
	/**
	 * Made with
	 */
	madeWithLoveBy: () => LocalizedString
	/**
	 * by cedhuf
	 */
	byAuthor: () => LocalizedString
	/**
	 * User permissions
	 */
	userPermissions: () => LocalizedString
	/**
	 * What signed-in users are allowed to do on this instance.
	 */
	userPermissionsDescription: () => LocalizedString
	/**
	 * Allow users to add their own provider connections
	 */
	allowUserProviders: () => LocalizedString
	/**
	 * Allow users to create their own personas
	 */
	allowUserPersonas: () => LocalizedString
	/**
	 * Locked — users can't change this
	 */
	lockedForUsers: () => LocalizedString
	/**
	 * Users may override for themselves
	 */
	overridableForUsers: () => LocalizedString
	/**
	 * Web search sharing
	 */
	webSearchSharing: () => LocalizedString
	/**
	 * Configure the search engine in the Chat tab; here you choose whether it's shared with users.
	 */
	webSearchSharingDescription: () => LocalizedString
	/**
	 * Share my search engine with users
	 */
	shareSearchEngine: () => LocalizedString
	/**
	 * No engine configured yet — set one up in the Chat tab first, then you can share it.
	 */
	noEngineConfigured: () => LocalizedString
	/**
	 * Currently sharing: {value}
	 */
	currentlySharing: (arg: { value: string }) => LocalizedString
	/**
	 * System prompts sharing
	 */
	systemPromptsSharing: () => LocalizedString
	/**
	 * Configure your prompts in the Chat tab; here you choose whether they're shared with all users (read-only for them). Per-user prompts will come with groups.
	 */
	systemPromptsSharingDescription: () => LocalizedString
	/**
	 * Share my system prompts with users
	 */
	shareSystemPrompts: () => LocalizedString
	/**
	 * Nothing configured yet — set up your prompts in the Chat tab to share something.
	 */
	noPromptsConfigured: () => LocalizedString
	/**
	 * Title generation sharing
	 */
	titleGenerationSharing: () => LocalizedString
	/**
	 * Share your title-generation settings (from the Chat tab) with users. The title model works even if it isn't in the shared models list.
	 */
	titleGenerationSharingDescription: () => LocalizedString
	/**
	 * Share my title generation with users
	 */
	shareTitleGeneration: () => LocalizedString
	/**
	 * Sharing
	 */
	sharingLabel: () => LocalizedString
	/**
	 * Shared models
	 */
	sharedModels: () => LocalizedString
	/**
	 * Pick which models from each system server are available to users. Configure the servers themselves in the Servers tab.
	 */
	sharedModelsDescription: () => LocalizedString
	/**
	 * No system servers yet — add one in the Servers tab.
	 */
	noSystemServers: () => LocalizedString
	/**
	 * Default model for users
	 */
	defaultModelForUsers: () => LocalizedString
	/**
	 * — none —
	 */
	none: () => LocalizedString
	/**
	 * Default — users may change it
	 */
	defaultUsersMayChange: () => LocalizedString
	/**
	 * Select models to share
	 */
	selectModelsToShare: () => LocalizedString
	/**
	 * {count} shared
	 */
	sharedCount: (arg: { count: number }) => LocalizedString
	/**
	 * No models available — check this server in the Servers tab.
	 */
	noModelsCheckServersTab: () => LocalizedString
	/**
	 * Users
	 */
	users: () => LocalizedString
	/**
	 * Accounts on this instance.
	 */
	usersDescription: () => LocalizedString
	/**
	 * Create a user
	 */
	createAUser: () => LocalizedString
	/**
	 * Initial password
	 */
	initialPassword: () => LocalizedString
	/**
	 * Create user
	 */
	createUser: () => LocalizedString
	/**
	 * Add user
	 */
	addUser: () => LocalizedString
	/**
	 * User created
	 */
	userCreated: () => LocalizedString
	/**
	 * Email and password are required
	 */
	emailAndPasswordRequired: () => LocalizedString
	/**
	 * Developer options
	 */
	developerOptions: () => LocalizedString
	/**
	 * Tools for checking flows a user normally only sees once.
	 */
	developerOptionsDescription: () => LocalizedString
	/**
	 * New-user onboarding
	 */
	newUserOnboarding: () => LocalizedString
	/**
	 * Replay the welcome tour. Closes this dialog; finishing it marks the tour as seen again.
	 */
	newUserOnboardingDescription: () => LocalizedString
	/**
	 * Launch
	 */
	launch: () => LocalizedString
	/**
	 * Search conversations
	 */
	searchConversations: () => LocalizedString
	/**
	 * Search in every conversation…
	 */
	searchConversationsPlaceholder: () => LocalizedString
	/**
	 * Search "{query}" in every conversation
	 */
	searchAllConversations: (arg: { query: string }) => LocalizedString
	/**
	 * {count} {{match|matches}}
	 */
	searchMatches: (arg: { count: number }) => LocalizedString
	/**
	 * Navigate
	 */
	searchNavigate: () => LocalizedString
	/**
	 * Open
	 */
	searchOpen: () => LocalizedString
	/**
	 * Close
	 */
	searchClose: () => LocalizedString
	/**
	 * Type to search the content of your conversations
	 */
	searchStart: () => LocalizedString
	/**
	 * Keyboard shortcuts
	 */
	keyboardShortcuts: () => LocalizedString
	/**
	 * What the app already listens for. Customising them will come later.
	 */
	keyboardShortcutsDescription: () => LocalizedString
	/**
	 * Anywhere
	 */
	shortcutsGlobal: () => LocalizedString
	/**
	 * Writing a message
	 */
	shortcutsComposer: () => LocalizedString
	/**
	 * Search dialog
	 */
	shortcutsSearch: () => LocalizedString
	/**
	 * Dialogs
	 */
	shortcutsDialogs: () => LocalizedString
	/**
	 * Send
	 */
	shortcutSendMessage: () => LocalizedString
	/**
	 * New line
	 */
	shortcutNewLine: () => LocalizedString
	/**
	 * In the expanded composer, {mod}↵ sends and ↵ inserts a line — so a long message can be written without firing on every return.
	 */
	shortcutExpandedNote: (arg: { mod: string }) => LocalizedString
	/**
	 * Move between tabs
	 */
	shortcutMoveBetweenTabs: () => LocalizedString
	/**
	 * Close
	 */
	close: () => LocalizedString
	/**
	 * Conversation load
	 */
	contextLoad: () => LocalizedString
	/**
	 * ~{tokens} of {limit} tokens ({percent}%)
	 */
	contextTokensOfLimit: (arg: { limit: string, percent: number, tokens: string }) => LocalizedString
	/**
	 * The model's context window (num_ctx)
	 */
	contextLimitFromModel: () => LocalizedString
	/**
	 * Threshold set in Settings → Chat
	 */
	contextLimitFromThreshold: () => LocalizedString
	/**
	 * {count} {{message|messages}} in context
	 */
	contextMessagesInContext: (arg: { count: number }) => LocalizedString
	/**
	 * {count} earlier {{message|messages}} summarised
	 */
	contextMessagesCompacted: (arg: { count: number }) => LocalizedString
	/**
	 * Estimated from text length, not counted by the provider.
	 */
	contextEstimateNote: () => LocalizedString
	/**
	 * {count} {{message|messages}} summarised
	 */
	contextCompacted: (arg: { count: number }) => LocalizedString
	/**
	 * Compacted automatically
	 */
	compactedAutomatically: () => LocalizedString
	/**
	 * Compacted on request
	 */
	compactedManually: () => LocalizedString
	/**
	 * Undo
	 */
	undoCompaction: () => LocalizedString
	/**
	 * Remove this summary and give the model the full history back
	 */
	undoCompactionHelp: () => LocalizedString
	/**
	 * Summarising the conversation…
	 */
	compacting: () => LocalizedString
	/**
	 * ~{tokens} tokens freed
	 */
	tokensFreed: (arg: { tokens: string }) => LocalizedString
	/**
	 * {before} down to {after}.
	 */
	tokensFreedDetail: (arg: { after: string, before: string }) => LocalizedString
	/**
	 * The conversation could not be compacted
	 */
	compactFailed: () => LocalizedString
	/**
	 * Commands
	 */
	slashCommands: () => LocalizedString
	/**
	 * Run
	 */
	slashRun: () => LocalizedString
	/**
	 * Summarise the conversation so far to free up context
	 */
	compactCommandDescription: () => LocalizedString
	/**
	 * This conversation is too short to be worth compacting
	 */
	nothingToCompact: () => LocalizedString
	/**
	 * Slash commands
	 */
	shortcutsCommands: () => LocalizedString
	/**
	 * Complete
	 */
	shortcutCompleteCommand: () => LocalizedString
	/**
	 * Type / at the start of an empty message to see the commands. A message that really starts with a slash is written //, and anything else — a path, a date — is sent as typed.
	 */
	shortcutCommandsNote: () => LocalizedString
	/**
	 * Compaction
	 */
	compaction: () => LocalizedString
	/**
	 * Summarise the earlier part of a conversation so it keeps fitting in the context window. Nothing is deleted — the summary replaces those messages only in what is sent, and can be undone.
	 */
	compactionDescription: () => LocalizedString
	/**
	 * Compaction model
	 */
	compactModel: () => LocalizedString
	/**
	 * Leave empty to use each conversation’s own model. Whatever this summary leaves out is lost to the assistant, so prefer a capable model over a cheap one.
	 */
	compactModelHelp: () => LocalizedString
	/**
	 * Compact automatically
	 */
	autoCompact: () => LocalizedString
	/**
	 * Summarise on its own once a conversation reaches the threshold below.
	 */
	autoCompactHelp: () => LocalizedString
	/**
	 * Threshold (tokens)
	 */
	compactThreshold: () => LocalizedString
	/**
	 * Also the ceiling the load indicator measures against when the provider does not announce its context window — which is most of them.
	 */
	compactThresholdHelp: () => LocalizedString
	/**
	 * each conversation’s model
	 */
	compactModelOwn: () => LocalizedString
	/**
	 * Compaction sharing
	 */
	compactionSharing: () => LocalizedString
	/**
	 * Share your compaction model and threshold with everyone on this instance.
	 */
	compactionSharingDescription: () => LocalizedString
	/**
	 * Share compaction settings
	 */
	shareCompaction: () => LocalizedString
}

export type Formatters = {}
