import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { env } from '$env/dynamic/private';
import { extensionFor } from '$lib/generatedImages';

/**
 * Where the pictures themselves live.
 *
 * Files under DATA_DIR, beside the database, so the one directory that is meant
 * to be bind-mounted still holds everything mutable. Not in SQLite: these are
 * megabytes that are only ever read whole and never queried, which is the one
 * shape a database is worst at and a filesystem is best at.
 *
 * One directory per account. Not for security (every read goes through a query
 * scoped to the owner before it gets here) but because it makes "what is this
 * person holding" and "delete this person" answerable with a path.
 */

/** A storage failure, as opposed to anything else that can go wrong drawing. */
export class ImageStoreError extends Error {}

function imagesDir(): string {
	return join(env.DATA_DIR?.trim() || './data', 'images');
}

/**
 * The path for one image.
 *
 * Both ids are generated by the app and are alphanumeric, but this is the
 * function that turns them into a filesystem path, so it is the function that
 * has to refuse anything else. A path is not the place to trust a caller.
 */
function pathFor(userId: string, id: string, contentType: string): string {
	if (!/^[A-Za-z0-9_-]+$/.test(userId) || !/^[A-Za-z0-9_-]+$/.test(id)) {
		throw new Error('Invalid image path');
	}
	return join(imagesDir(), userId, `${id}.${extensionFor(contentType)}`);
}

/**
 * Why a write failed, in words somebody can act on.
 *
 * Kept apart from the errno because the two audiences are different. Whoever
 * pressed the button needs to know this is the instance and not their prompt;
 * whoever runs the instance needs the path and the code, and gets them in the
 * log. So one sentence goes back, the detail stays on the server, and the two
 * are never the same string.
 *
 * The reasons are the three that actually happen to a directory somebody
 * bind-mounted: it is not theirs to write in, it is mounted read only, or it is
 * out of room. Everything else is honestly unknown rather than guessed at.
 */
function whyWriteFailed(cause: unknown): string {
	const code = (cause as { code?: string })?.code;
	if (code === 'EACCES' || code === 'EPERM') {
		return 'The server cannot write to its image directory. Check who owns it.';
	}
	if (code === 'EROFS') return 'The server image directory is mounted read only.';
	if (code === 'ENOSPC') return 'The server has no disk space left for images.';
	return 'The server could not store the image.';
}

export function writeImage(
	userId: string,
	id: string,
	contentType: string,
	bytes: Uint8Array
): void {
	const path = pathFor(userId, id, contentType);
	const dir = join(imagesDir(), userId);
	try {
		mkdirSync(dir, { recursive: true });
		writeFileSync(path, bytes);
	} catch (cause) {
		// Loud, and with the path in it. This used to surface as `Internal Error`
		// and nothing else, which sent somebody reading a stack trace to find out
		// that a directory had the wrong owner.
		console.error(`[images] cannot write ${dir}:`, cause);
		throw new ImageStoreError(whyWriteFailed(cause));
	}
}

/**
 * The bytes, or nothing when the file is gone and the row outlived it.
 *
 * The path is built before the catch, on purpose. Inside it, a refused path and
 * a missing file would come back as the same answer, and "no such image" is
 * exactly the wrong way to report an id that should never have reached here:
 * a malformed one is a bug or an attempt, and either deserves to be loud.
 *
 * A missing file stays quiet, because it is an ordinary thing: a row can outlive
 * its bytes. Anything else is said out loud. A directory the server may not read
 * makes every picture in the gallery vanish, one silent `undefined` at a time,
 * and looks exactly like an empty gallery. That is the failure that hides longest.
 */
export function readImage(userId: string, id: string, contentType: string): Buffer | undefined {
	const path = pathFor(userId, id, contentType);
	try {
		return readFileSync(path);
	} catch (cause) {
		if ((cause as { code?: string })?.code !== 'ENOENT') {
			console.error(`[images] cannot read ${path}:`, cause);
		}
		return undefined;
	}
}

/** Remove one file. A file that is already gone is a success, not an error. */
export function removeImage(userId: string, id: string, contentType: string): void {
	const path = pathFor(userId, id, contentType);
	try {
		rmSync(path, { force: true });
	} catch {
		// The row is what makes an image exist. A file left behind is wasted disk,
		// not a failed deletion, and throwing here would leave the row instead.
	}
}
