import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { env } from '$env/dynamic/private';
import { extensionFor } from '$lib/generatedImages';

/**
 * Where the pictures themselves live: files under DATA_DIR, beside the database,
 * so the one bind-mounted directory holds everything mutable. Not in SQLite:
 * megabytes only ever read whole and never queried.
 *
 * One directory per account, not for security but because it makes "what is this
 * person holding" and "delete this person" answerable with a path.
 */

/** A storage failure, as opposed to anything else that can go wrong drawing. */
export class ImageStoreError extends Error {}

function imagesDir(): string {
	return join(env.DATA_DIR?.trim() || './data', 'images');
}

/** Both ids are generated by the app, but this is the function that turns them into a filesystem path, so it is the one that has to refuse anything else. */
function pathFor(userId: string, id: string, contentType: string): string {
	if (!/^[A-Za-z0-9_-]+$/.test(userId) || !/^[A-Za-z0-9_-]+$/.test(id)) {
		throw new Error('Invalid image path');
	}
	return join(imagesDir(), userId, `${id}.${extensionFor(contentType)}`);
}

/**
 * Why a write failed, in words somebody can act on. Whoever pressed the button
 * needs to know this is the instance and not their prompt; whoever runs it needs
 * the path and the code, and gets them in the log.
 *
 * The three that actually happen to a bind-mounted directory: not theirs to
 * write in, mounted read only, or out of room. Everything else is honestly
 * unknown rather than guessed at.
 */
function whyWriteFailed(cause: unknown): string {
	const code = (cause as { code?: string })?.code;
	if (code === 'EACCES' || code === 'EPERM') {
		return 'The server cannot write to its image directory. Check who owns it.';
	}
	if (code === 'EROFS') return 'The server image directory is mounted read only.';
	if (code === 'ENOSPC') return 'The server has no disk space left for images.';
	return 'The server could not store the image.';
}

export function writeImage(
	userId: string,
	id: string,
	contentType: string,
	bytes: Uint8Array
): void {
	const path = pathFor(userId, id, contentType);
	const dir = join(imagesDir(), userId);
	try {
		mkdirSync(dir, { recursive: true });
		writeFileSync(path, bytes);
	} catch (cause) {
		// Loud, and with the path in it: this used to surface as `Internal Error` and
		// nothing else.
		console.error(`[images] cannot write ${dir}:`, cause);
		throw new ImageStoreError(whyWriteFailed(cause));
	}
}

/**
 * The bytes, or nothing when the file is gone and the row outlived it.
 *
 * The path is built before the catch on purpose: inside it, a refused path and a
 * missing file would come back the same, and a malformed id is a bug or an
 * attempt, which deserves to be loud.
 *
 * A missing file stays quiet, being ordinary. A directory the server may not
 * read makes every picture vanish one silent `undefined` at a time, and looks
 * exactly like an empty gallery.
 */
export function readImage(userId: string, id: string, contentType: string): Buffer | undefined {
	const path = pathFor(userId, id, contentType);
	try {
		return readFileSync(path);
	} catch (cause) {
		if ((cause as { code?: string })?.code !== 'ENOENT') {
			console.error(`[images] cannot read ${path}:`, cause);
		}
		return undefined;
	}
}

/** Remove one file. A file that is already gone is a success, not an error. */
export function removeImage(userId: string, id: string, contentType: string): void {
	const path = pathFor(userId, id, contentType);
	try {
		rmSync(path, { force: true });
	} catch {
		// The row is what makes an image exist: a file left behind is wasted disk, not a
		// failed deletion, and throwing would leave the row instead.
	}
}
