import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { env } from '$env/dynamic/private';
import { extensionFor } from '$lib/generatedImages';

/**
 * Where the pictures themselves live.
 *
 * Files under DATA_DIR, beside the database, so the one directory that is meant
 * to be bind-mounted still holds everything mutable. Not in SQLite: these are
 * megabytes that are only ever read whole and never queried, which is the one
 * shape a database is worst at and a filesystem is best at.
 *
 * One directory per account. Not for security (every read goes through a query
 * scoped to the owner before it gets here) but because it makes "what is this
 * person holding" and "delete this person" answerable with a path.
 */

function imagesDir(): string {
	return join(env.DATA_DIR?.trim() || './data', 'images');
}

/**
 * The path for one image.
 *
 * Both ids are generated by the app and are alphanumeric, but this is the
 * function that turns them into a filesystem path, so it is the function that
 * has to refuse anything else. A path is not the place to trust a caller.
 */
function pathFor(userId: string, id: string, contentType: string): string {
	if (!/^[A-Za-z0-9_-]+$/.test(userId) || !/^[A-Za-z0-9_-]+$/.test(id)) {
		throw new Error('Invalid image path');
	}
	return join(imagesDir(), userId, `${id}.${extensionFor(contentType)}`);
}

export function writeImage(
	userId: string,
	id: string,
	contentType: string,
	bytes: Uint8Array
): void {
	const path = pathFor(userId, id, contentType);
	mkdirSync(join(imagesDir(), userId), { recursive: true });
	writeFileSync(path, bytes);
}

/**
 * The bytes, or nothing when the file is gone and the row outlived it.
 *
 * The path is built before the catch, on purpose. Inside it, a refused path and
 * a missing file would come back as the same answer, and "no such image" is
 * exactly the wrong way to report an id that should never have reached here:
 * a malformed one is a bug or an attempt, and either deserves to be loud.
 */
export function readImage(userId: string, id: string, contentType: string): Buffer | undefined {
	const path = pathFor(userId, id, contentType);
	try {
		return readFileSync(path);
	} catch {
		return undefined;
	}
}

/** Remove one file. A file that is already gone is a success, not an error. */
export function removeImage(userId: string, id: string, contentType: string): void {
	const path = pathFor(userId, id, contentType);
	try {
		rmSync(path, { force: true });
	} catch {
		// The row is what makes an image exist. A file left behind is wasted disk,
		// not a failed deletion, and throwing here would leave the row instead.
	}
}
